### ISSUE TITLE
[discuss] API implementation visibility/packages

### ISSUE THREAD

**Issue by lburgazzoli** [coreos/jetcd#116]
The package com.coreos.jetcd contains both the interface definition and the related implementations that cane be instantiated as they are public and have a public constructor so I think it would be nice to do eithe make the visibility of the implemntation classes as package scope or move them to com.coreos.jetcd.internal.impl so at least the name mark them as non public.

Thoughts ?

**Comment by fanminshi** [comment]
I am fine with moving impl classes to `com.coreos.jetcd.internal.impl` folder.

**Comment by xiang90** [comment]
@lburgazzoli is this already fixed?

**Comment by lburgazzoli** [comment]
yes it is
