### ISSUE TITLE
Is this api fully support v3 api for etcd server and is it authorization and connection pooling issue is resolved with this?

### ISSUE THREAD

**Issue by suresh-chaudhari** [coreos/jetcd#124]
please confirm above question.

**Comment by fanminshi** [comment]
`Is this api fully support v3 api for etcd server`
It supports most of v3 apis excepts few such hash(), locking, and leader election. Support locking and leader election api is not critical for now but can be added later. 

`is it authorization and connection pooling issue is resolved with this?`
I don't understand what you mean by `authorization and connection pooling issue`. Could you elaborate?

**Comment by fanminshi** [comment]
close due to inactivity. please reopen when have more questions.
