### ISSUE TITLE
I want to know whether jetcd supports https ?

### ISSUE THREAD

**Issue by riclava** [coreos/jetcd#131]
same with title

**Comment by fanminshi** [comment]
cc/ @lburgazzoli

**Comment by lburgazzoli** [comment]
See #55

**Comment by fanminshi** [comment]
@riclava it does support now via https://github.com/coreos/jetcd/pull/161.

**Comment by riclava** [comment]
@fanminshi thanks a lot ;-)

**Comment by alkismavridis** [comment]
I still cannot activate TLS with jetcd.

Following the instructions  [here](https://github.com/grpc/grpc-java/blob/master/SECURITY.md#tls-with-netty-tcnative-on-boringssl), I had to add the following to my gradle dependencies:
```
compile group: 'io.grpc', name: 'grpc-all', version: '1.15.1'
runtime 'io.netty:netty-tcnative-boringssl-static:2.0.12.Final

```

Which results to java.lang.NoSuchMethodError: io.netty.internal.tcnative.SSLContext.setCipherSuite(JLjava/lang/String;Z)Z on linux.

After spending tones of time, I got this working by replacing the gradle demendencies mentioned above with 
```
compile group: 'io.netty', name: 'netty-handler', version: '4.1.27.Final'
compile group: 'io.grpc', name: 'grpc-all', version: '1.15.1'
compile group: 'io.netty', name: 'netty-tcnative-boringssl-static', version: '2.0.12.Final'
compile group: 'com.coreos', name: 'jetcd-core', version: '0.0.2'
```

This works fine locally, but breaks in my bamboo server while running the tests.
The message is:
`Could not find TLS ALPN provider; no working netty-tcnative, Conscrypt, or Jetty NPN/ALPN available`

I worked around this by introducing an ugly if statement that wrapped the whole thing and that is not executed in tests.

The current way of dealing with TLS seems very confusing to me...
Any help or advice is most welcome.

**Comment by lburgazzoli** [comment]
looks like you are using incompatible versions, can you test against the latest available jetcd release ?

**Comment by alkismavridis** [comment]
Sure! I will do it right now.

**Comment by alkismavridis** [comment]
Ok, I think I already use the latest jetcd.
Here is my dependency:
`io.etcd:jetcd-core:0.4.1`

**Comment by alkismavridis** [comment]
EDIT:
I upgraded the io.grpc and followed the table [here](https://github.com/grpc/grpc-java/blob/master/SECURITY.md) to find the corresponding netty:netty-tcnative-boringssl-static version.

I ended up with the following dependencies:
```
    compile 'io.etcd:jetcd-core:0.4.1'
    compile group: 'io.grpc', name: 'grpc-all', version: '1.27.1'
    compile group: 'io.netty', name: 'netty-tcnative-boringssl-static', version: '2.0.26.Final'

```

Locally it works fine. Unit tests too.
In build server I get:
`Factory method 'etcdClient' threw exception; nested exception is java.lang.IllegalStateException: Could not find TLS ALPN provider; no working netty-tcnative, Conscrypt, or Jetty NPN/ALPN available`

This means that I will probably have to re-introduce the hacky if-statement that I mentioned above.

**Comment by lburgazzoli** [comment]
what is your build server ? maybe it is not one of the supported os

**Comment by alkismavridis** [comment]
There are multiple build servers. Some of them run oracle linux and some redhat.
Yes, maybe it is not supported.
The weird thing is that we use https (for example spring's RestTemplate) without any problems nor any need for additional dependencies. How do those work?

So, any suggestion is very welcome. Giving up etcd is not an option...

**Comment by lburgazzoli** [comment]
It's really hard to provide an answe, we do run on test on travis and/or github actions that are bot running on ubuntu but it should work on any other system.

**Comment by alkismavridis** [comment]
Ok thanks a lot for your time. It looks like I will not get https working... :(

I am not sure how others deal with https (for example, RestTemplate), but they do it great. And we, as users, do not have to isntall extra dependencies, or deal with system compatibility issues like mine.

It would be **awesome** if you also find a similar way of doing it.
In any case, thanks a lot for your time.
