### ISSUE TITLE
[discuss] delay channel creation/authentication 

### ISSUE THREAD

**Issue by lburgazzoli** [coreos/jetcd#133]
If I properly understood etcd set-ups channels and eventually authentication on constructors (Client, KVImpl, etc) but that may be a little bit early so it would be nice to have an option to delay it to later stage i.e. when the first request is made.

Does it make sense ?

**Comment by fanminshi** [comment]
I am curious on how the delay channel creation logic look like.

Current logic.
1. create channel in client.
2. pass the channel to construct different client Impl.
3. made a request on using different client impl.

delay logic?
to create channel when step 3 happens? I wonder what's your proposal on doing that?

can you elaborate on `authentication on constructors`? I am not sure if I understand what you mean.

**Comment by lburgazzoli** [comment]
Yeah, I mean to eventually delay the initialization of the client and the authentication to the 3rd step.

Looking at the Client implementation I see:
1. the constructor invokes [toChannelAndToken](https://github.com/coreos/jetcd/blob/master/src/main/java/com/coreos/jetcd/Client.java#L85)
2. toChannelAndToken create a cahnel manager and invokes [generateToken](https://github.com/coreos/jetcd/blob/master/src/main/java/com/coreos/jetcd/Client.java#L103)
3. generateToken eventually perform the authentication with provided user name and password

So this lead to a connection and thus a possible exception at constructor phase which in some case you may want to delay.

**Comment by fanminshi** [comment]
@lburgazzoli I think delaying connection creation is an optimization. I haven't see any issues related by current approach. I'd suggest that implementing the delaying logic when needed.

**Comment by lburgazzoli** [comment]
It is my use case where I'd like to create the client instance in spring and only connect when the specific client i.e the kv one is created. As today I have delay the client creation at the latest stage si that I can eventually handle the exception.

**Comment by fanminshi** [comment]
`As today I have delay the client creation at the latest stage si that I can eventually handle the exception.`
I wonder are you trying to handle client specific exception at `client.getKVClient()` so that you can somehow reason about creating client error?

Also it seems to me that you could have a ClientWrapper class that does lazy client initialization. When ClientWrapper.getKVClient() called.
1. create jetcd client if it hasn't been created and handle exception there.
2. return jetcd `client.getKVClient()`.

**Comment by lburgazzoli** [comment]
Yes, I need to catch the exception when the app is ready so I can properly report it but as today if I one sets up the client i.e. using spring boot it may get an exception while the application context is starting up. 

Yes there are may way to lazy create the client but I wanted to point out that optionally laziness in resource creation may be a nice to have option. 

I can work on a prototype if needed.

**Comment by fanminshi** [comment]
@lburgazzoli  sounds good. it will be great if you can work on a prototype.

**Comment by fanminshi** [comment]
Thank you for the pr. closed via #148
