### ISSUE TITLE
Is ByteSequence necessary? 

### ISSUE THREAD

**Issue by smartminghan** [coreos/jetcd#145]
May i know if ByteSequence is necessary?  GRPC interface require us to input ByteString param as key and value. why not just directly use ByteString.copyFrom("targetString")  to return ByteString ?  Look forward to your reply.

**Comment by fanminshi** [comment]
The reason for using ByteSequence  instead of Bytestring is to hide implementation detail. Jetcd interface shouldn't depend on protobuf type.

**Comment by smartminghan** [comment]
Then why not just use String as Jetcd interface's param?  In implementation we can transform String to ByteString directly.

**Comment by fanminshi** [comment]
@smartminghan what if you don't want to use string as the key but with arbitrary bytes? have an interface that takes bytes is more generic.

**Comment by fanminshi** [comment]
closing. reopen if you have more questions.
