### ISSUE TITLE
ClientBuilder method naming

### ISSUE THREAD

**Issue by lburgazzoli** [coreos/jetcd#147]
ClientBuilder follows different naming conventions as there is a mix of builder style naming and get/set style, i.e. :

   ClientBuilder.endpoints(...)
   ClientBuilder.setPassword

As this is a builder it would be better to use builder style naming:
    
    ClientBuilder password(ByteSequence password) { ... }
    ByteSequence password() { ... }

Am I missing something ?

**Comment by fanminshi** [comment]
@lburgazzoli I agree with you. the naming should be consistent. I think the convention is to have `set*()` prefix. `ClientBuilder.endpoints(...)` -> `ClientBuilder.setEndpoints(...)`?
