### ISSUE TITLE
[design]: add internal package to hide our implementation details

### ISSUE THREAD

**Issue by skyao** [coreos/jetcd#15]
I would like to add a internal package such as "com.coreos.jetcd.internal" and move some implementation classes like EtcdKVImpl to it.

And we should document that all the classes in package internal are our internal implementation detail and should not be used directly. 

Then We can update them freely.

**Comment by AdoHe** [comment]
@skyao I already have a [design proposal](https://github.com/AdoHe/etcd4j/issues/13) when I try to implement this client, you may take a look.

**Comment by fanminshi** [comment]
"com.coreos.jetcd.internal" is added.
