### ISSUE TITLE
Semantic versioning

### ISSUE THREAD

**Issue by nbrauer** [coreos/jetcd#150]
Right now the version for jetcd is hard coded at 0.1.0-SNAPSHOT. All of the code changes are getting lumped under that version. When I upgrade to the latest code, there are build breakages because classes have been renamed and signatures have changed. 

For people like me who would like to use jetcd in my projects it's difficult to experiment with because upgrading means that I am potentially hit by breaking changes. Implementing Semver would help early adopters like myself use jetcd with less fear that an upgrade is going to break my build.

**Comment by xiang90** [comment]
It is too early to even use Semver. We will start using semver when we feel it is alpha quality software at least...

**Comment by fanminshi** [comment]
@nbrauer sorry for all the changes going on right. we are trying hard to get the alpha version out; so a lot changes are being made to make sure that the interfaces and implementations are good.

**Comment by fanminshi** [comment]
@nbrauer push first release to maven central https://search.maven.org/#search%7Cga%7C1%7Ccoreos
