### ISSUE TITLE
Client interfaces

### ISSUE THREAD

**Issue by lburgazzoli** [coreos/jetcd#16]
I'm wondering if it could make sense to enhance client interface with convenient methods i.e:
- Options should not be mandatory:

``` java
ListenableFuture<PutResponse> put(ByteString key, ByteString value);
```
- Leverage java 8 functional interfaces (if project will be moved to java 8 of course):

``` java
void put(
   ByteString key, ByteString value, 
   PutOption option, 
   Consumer<PutResponse> onResponse, Consumer<Throwable> onError);

void put(
   ByteString key, ByteString value, 
   Consumer<PutResponse> onResponse, Consumer<Throwable> onError);

void put(
   ByteString key, ByteString value, 
   Consumer<PutResponse> onResponse); throws an RuntimeException in case of error
```

**Comment by jurmous** [comment]
My preference would be to return java 8 CompletableFuture on any of those put calls. It seems to be the route for futures/listeners in java going forward. You would then be able to do this:

```
future.handle((ok, ex) -> {
    if (ok != null) {
        // handle ok
    } else {
        handle error
    }
});
```
or just ``` future.get() ``` for sync call and throws ExecutionException

More:
http://www.nurkiewicz.com/2013/05/java-8-definitive-guide-to.html
http://download.java.net/lambda/b88/docs/api/java/util/concurrent/CompletableFuture.html

**Comment by lburgazzoli** [comment]
The only problem is that grpc layer returns a ListenableFuture so we neeed to wrap/convert it, or is ther any better way ?

**Comment by AdoHe** [comment]
SGTM.

**Comment by xiang90** [comment]
@lburgazzoli we should do suggestion 1 for sure. can you help to improve that?

/cc @sijie what's your opinion on suggestion2?

**Comment by lburgazzoli** [comment]
I've a patch (https://github.com/lburgazzoli/coreos-jetcd/commit/9f287c89a3bc0e22b3f782dff39f9c4b2e389e47) that should implement both (suggestion 2 using CompletableFutureas suggested by @jurmous). It includes an additional dependency at the moment for quick prototyping

**Comment by jurmous** [comment]
Ah I did not look into grpc yet... Wrapping would create overhead but at the same time it is I think good to hide away implementation details which could change in the future. Don't know if there are alternatives with grpc and guava ListenableFutures than wrapping.

**Comment by lburgazzoli** [comment]
Let me know what you think about lburgazzoli@9f287c8 so I can send a PR

**Comment by sijie** [comment]
re the second question:

@xiang90 @lburgazzoli @jurmous  since we haven't thought of what is the best structures for returning to users, I would suggest using the ListenableFuture generated by grpc for now. It seems to me it is only a wrapper for converting ListenableFuture to CompletableFuture, so don't seem to be a big deal though. Also, the interface is marked as Beta for now. We can iterate the interface once we complete most of the implementations.

**Comment by oza** [comment]
FYI, as I mentioned [here](https://github.com/coreos/jetcd/pull/45#discussion_r76964462), I think we should avoid using ByteString generated by protobuf directly.
