### ISSUE TITLE
UNAUTHENTICATED: etcdserver: invalid auth token

### ISSUE THREAD

**Issue by foolonhill** [coreos/jetcd#163]
When i use kv client, i first build Client with auth when service startup. But after about 5 minutes, if i get KVClient form the built client to put a key/vaule when necessary, "Client.getKVClient().put(key, value).get();" will result in this exception. Client builder is as below: 
```
Client client = ClientBuilder.newBuilder().setEndpoints(endpoints).setUser(name).setPassword(pwd).build();
```
I wonder whether the auth token will be expire in about 5minutes. And does the token will be generated automatically in jetcd when a command is to be excuted? If not, how should i do ?

**Comment by fanminshi** [comment]
`first build Client with auth when service startup`
Could you provide the script for this as well? It will help me debug this.

**Comment by foolonhill** [comment]
Client build is just as below when service start. It is built just once. For i use etcd in a web application, i build the Client in the init parse when the web application is started.
`Client client = ClientBuilder.newBuilder().setEndpoints(endpoints).setUser(name).setPassword(pwd).build();`

Then i use KVClient to put key when necessary. But after the application has started more than 5min, the get() interface will result in the "invalid auth token" exception, and the put command will not take effect.
`Client.getKVClient().put(key, value).get()`

**Comment by foolonhill** [comment]
I have tried two methods to solve my problem. And each one dose work.
1. Build client each time when i use etcd, that is, **every time** i use KV or Watch or Lease, i need explicit build the Client by follow codes;
`Client client = ClientBuilder.newBuilder().setEndpoints(endpoints).setUser(name).setPassword(pwd).build();`

2. I modify the latest jetcd code to generate token each time when i getXXXClient form the first built Client.
I modify two function: 
*  com.coreos.jetcd.internal.impl.ClientImpl
```
private <T extends CloseableClient> T newClient(
    AtomicReference<T> reference, Function<ClientConnectionManager, T> factory) {
  //    T client = reference.get();
  //
  //    if (client == null) {
  //      synchronized (reference) {
  //        client = reference.get();
  //        if (client == null) {
  //          client = factory.apply(connectionManager);
  //          reference.lazySet(client);
  //        }
  //      }
  //    }
  //
  //    return client;
  return factory.apply(connectionManager);
}
```


*  com.coreos.jetcd.internal.impl.ClientConnectionManager

```
Optional<String> getToken() {
  //    Optional<String> tk = tokenRef.get();
  //    if (tk == null) {
  //      synchronized (tokenRef) {
  //        tk = tokenRef.get();
  //        if (tk == null) {
  //          tk = generateToken(getChannel(), builder.getUser(), builder.getPassword());
  //          tokenRef.lazySet(tk);
  //        }
  //      }
  //    }
  //
  //    return tk;
  return generateToken(getChannel(), builder.getUser(), builder.getPassword());
}
```

**Comment by fanminshi** [comment]
@foolonhill how are you setting up user?

java client requires you setup user beforehand before building a client with user and pass enabled.

e.g
```java
  public void testIssue163() throws ExecutionException, InterruptedException {
    Client client = ClientBuilder.newBuilder()
        .setEndpoints("http://localhost:2379")
        .build();

    // create auth client
    Auth authClient = client.getAuthClient();

    // add root
    ByteSequence root = ByteSequence.fromString("root");
    ByteSequence rootpass = ByteSequence.fromString("123");
    authClient.userAdd(root, rootpass).get();

    // add role rootRole
    ByteSequence rootRole = ByteSequence.fromString("root");
    authClient.roleAdd(rootRole);

    // grant root with rootRole
    authClient.userGrantRole(root, rootRole).get();

    // add user
    ByteSequence user = ByteSequence.fromString("user");
    ByteSequence pass = ByteSequence.fromString("123");
    authClient.userAdd(user, pass).get();

    // add role userRole
    ByteSequence roleName = ByteSequence.fromString("root");
    authClient.roleAdd(roleName);

    // grant userRole read writes on all ranges
    ByteSequence keyRangeBegin = ByteSequence.fromString("");
    ByteSequence keyRangeEnd = ByteSequence.fromString("");
    authClient
        .roleGrantPermission(roleName, keyRangeBegin, keyRangeEnd, Permission.Type.READWRITE).get();
    authClient.userGrantRole(user, roleName).get();

    // enable anth
    AuthEnableResponse response = authClient.authEnable().get();

    // create client with user and pass
    Client secureClient = ClientBuilder.newBuilder()
        .setEndpoints("http://localhost:2379")
        .setUser(root)
        .setPassword(rootpass).build();

    // test secureClient put
    ByteSequence key = ByteSequence.fromString("key");
    ByteSequence value = ByteSequence.fromString("value");
    secureClient.getKVClient().put(key, value).get();
    GetResponse getResponse = secureClient.getKVClient().get(key).get();
    System.out.println(getResponse.getKvs().get(0).getKey().toStringUtf8());
    // output: key
  }
```

**Comment by foolonhill** [comment]
@fanminshi , i set user and role in etcd server and enable in server too. I do this follow :
https://github.com/coreos/etcd/blob/master/Documentation/op-guide/authentication.md

**Comment by lburgazzoli** [comment]
@xiang90 @fanminshi 

is there any doc on etcd side explaining hot this should be handled ?
how does other implementations like go client behaves within this case ?

**Comment by foolonhill** [comment]
@fanminshi @lburgazzoli 
i found another one discuss this problem. https://github.com/davissp14/etcdv3-ruby/issues/74

**Comment by fanminshi** [comment]
@foolonhill Jetcd should renew token if it is expired and retry the given request with user's intervention. @lburgazzoli  KV and Lease in Go Client has a retry mechanism as the following

0. request something
1. etcd detects token has expired and return `etcdserver: invalid auth token` to client.
2. client re-generates token 
3. client replaces old token with the new one for the existing underlying channel/connection. 
4. retry the request automatically.

note. still need to figure out which APIs needs the support of this type of retry.

**Comment by lburgazzoli** [comment]
@fanminshi 

So if I properly understood what the go client does is wrapping the kv client like

```java
class KVWrapper implements KV {
    KV delegate;

    public PutResponse put(...) {
        try {
            return delegate.put(...)
        } catch (ExpiredTokenException e) {
            delegate.refreshToken()
            delegate.put(...) 
        }
    }
}
```

**Comment by fanminshi** [comment]
@lburgazzoli yep, that's the idea. the go client also automatic retry on grpc transient error. we don't have to implement that now. However, retry on `ErrInvalidAuthToken` is needed to client to work properly.

**Comment by donsonHub** [comment]
so when to fix the bug?

**Comment by donsonHub** [comment]
@fanminshi so when to fix the bug?

**Comment by fanminshi** [comment]
@donsonHub it is working in progress.
