### ISSUE TITLE
client: add doc on how to set up tls

### ISSUE THREAD

**Issue by fanminshi** [coreos/jetcd#164]

**Comment by fanminshi** [comment]
@lburgazzoli have you successfully set up tls with jetcd?

**Comment by lburgazzoli** [comment]
not yet, will have a look when get back from holidays

**Comment by lburgazzoli** [comment]
@fanminshi I'm a little busy at the moment so I can't have a look at this

**Comment by fanminshi** [comment]
@lburgazzoli not a problem. I am digging into this now.

**Comment by fanminshi** [comment]
fixed via https://github.com/coreos/jetcd/issues/162
