### ISSUE TITLE
there are 2 class named PutResponse

### ISSUE THREAD

**Issue by chenyouhuang** [coreos/jetcd#165]
why not use some class that protoc has generated like PutResponse directly? instead, declared other class named PutResponse and use it and you must transform each other. I compare the two class, its property are same. I'm confuse on this.

**Comment by fanminshi** [comment]
Jetcd interface shouldn't depend on any internal technology. If the APIs returns protobuf message directly, then jetcd must depends on protobuf. Suppose jetcd is move away grpc/protobuf, then interface would have to change and thus breaks existing api. In addition, suppose that we return protobuf message directly where in future new protobuf version changes structure of generated message. Then it breaks the code that is written depended on old protobuf msg. By having a custom message type avoids all above.

Also google official doc doesn't think protobuf classes is first class citizens in an object model.

"Protocol Buffers and O-O Design Protocol buffer classes are basically dumb data holders (like structs in C); they don't make good first class citizens in an object model. If you want to add richer behaviour to a generated class, the best way to do this is to wrap the generated protocol buffer class in an application-specific class. Wrapping protocol buffers is also a good idea if you don't have control over the design of the .proto file (if, say, you're reusing one from another project). In that case, you can use the wrapper class to craft an interface better suited to the unique environment of your application: hiding some data and methods, exposing convenience functions, etc. You should never add behaviour to the generated classes by inheriting from them. This will break internal mechanisms and is not good object-oriented practice anyway."
https://developers.google.com/protocol-buffers/docs/javatutorial?csw=1#parsing-and-serialization

**Comment by heyitsanthony** [comment]
@fanminshi the server API isn't going to drop grpc/protobuf or change the protobuf messages/structure; protobuf is a hard dependency. If there's a move away from protobuf, that's going to be an API refresh and the client should change to reflect it so there's a good correspondence with the RPCs and messages.

The main motivation behind wrapping the protobuf stubs is that they're very primitive; if the stubs are enough then there's no need to have a special client. It might be reasonable to extend the protobuf objects instead of duplicating everything.

**Comment by xiang90** [comment]
> It might be reasonable to extend the protobuf objects instead of duplicating everything.

for go, we cannot easily do this since it is not allowed to add new methods out of a pkg. same thing for java, right?

**Comment by heyitsanthony** [comment]
@xiang90 java will let you do that, but the protobuf stub classes are all marked `final` which prevents it.

**Comment by chenyouhuang** [comment]
In addition, auth api and cluster api is depend on protoc message directly, i think its not unify.

**Comment by xiang90** [comment]
@chenyouhuang yea. we are fixing them right now. if you have time, you can help to unify them too.

**Comment by fanminshi** [comment]
https://github.com/coreos/jetcd/pull/153 is for auth api.

**Comment by chenyouhuang** [comment]
Thank you for your rapid response. Because i am using jetcd in my project and find it some duplicate, so have this questions.
