### ISSUE TITLE
build: add maven wrapper

### ISSUE THREAD

**Issue by lburgazzoli** [coreos/jetcd#174]
By using a maven wrapper [1] we can be sure that the the project can be built even if maven is not installed and that the build always use the right maven version. 

[1] https://github.com/takari/maven-wrapper

**Comment by fanminshi** [comment]
@lburgazzoli sounds like a good idea to me. Do you know if this is a best practice for java project that depends on maven?

**Comment by lburgazzoli** [comment]
Yeah, lot of projects (i.e. spring) are doing so (for both maven and gradle)

**Comment by fanminshi** [comment]
@lburgazzoli cool. Let's do this then.

**Comment by fanminshi** [comment]
let me tackle this as i want to learn how this work.

**Comment by fanminshi** [comment]
@lburgazzoli would you be interested in doing this. I saw that your etcd4j already has this included.

**Comment by fanminshi** [comment]
close via https://github.com/coreos/jetcd/pull/186
