### ISSUE TITLE
[discuss] remove name resolver factory from ClientBuilder

### ISSUE THREAD

**Issue by lburgazzoli** [coreos/jetcd#176]
As today we have the possibility to set the name resolver factory on the client builder but it may be better to determine the resolver to use based on the scheme used for the endpoints so i.e.

```java
    // Use the simple resolver
    ClientBuilder.newBuilder().setEndpoints("http://node1:2379", ...)

    // Use the dns+srv resolver
    ClientBuilder.newBuilder().setEndpoints("dns+srv://_etcd-server._tcp.")
```

They can also be mixed and if an advanced user needs to apply advanced configuration to the underlying channel it can provide its own ManagedChannelBuilder as today.

**Comment by fanminshi** [comment]
@lburgazzoli I need sometime to think about this. 
Eventually, I want to add 
`void SetEndpoints(List<String> endpoints)`  function to `client` where this function
allows user to updates endpoints dynamically.  
https://github.com/coreos/etcd/blob/master/clientv3/client.go#L119-L122

if `newBuilder().setEndpoints` only accepts `http/https` then `client.SetEndpoints` only update endpoints for scheme `http/https`. If we introduce more sheme such as `dns+srv` in `newBuilder().setEndpoints(`. Then how what's the expectation of ``client.SetEndpoints` on endpoint with scheme `dns+srv`.

**Comment by lburgazzoli** [comment]
It would do the same: it goes down to the resolver and it is up to the resolver to update the right underlying resolver.

```java
for (MyResolver resolver : resolvers) {
    // each resolver updates its endpoint list
    // only if it can handle the given scheme
    resolver.update(endpoints);
}
```

But I'm not a big fan to have a mixed way to set options as in general it cause confusion, maybe we can have something like:

```java
ImmutableEndpointList endpoints = EndpointsList.immutable(...)
Builder.setEndpoints(endpoints)
```
And:

```java
MutableEndpointList endpoints = EndpointsList.mutable(...)
Builder.setEndpoints(endpoints)

endpoints.update(...)
```

**Comment by fanminshi** [comment]
@lburgazzoli i agree with on this. I don't like mix options too.  the idea of setting resolver based on the scheme  sounds good to me.  cc/ @xiang90

**Comment by lburgazzoli** [comment]
If you guys approve I can work on it

**Comment by fanminshi** [comment]
@lburgazzoli talked to @xiang90 in person. We think that the endpoints from `setEndpoints ` should  always associate to name resolver if there is one given; we need to document this expectation so that there shouldn't be any confusion. If name resolver not given, then we can be smart about choosing the default resolver(simple or dns) base on scheme. I think this approach gives users flexibility to implement their own resolver and have their own endpoint format.

**Comment by lburgazzoli** [comment]
Yeah but there is a problem: endpoints and name resolver are not linked :)

If you look at the documentation of ``NameResolver`` and ``NameResolver.Factory``  you'd see that the implementation relies on the ``target`` or a single address argument you can set with 
 ``ManagedChannelBuilder.forTarget/forAddress``.

Our ``SimpleResolver*`` does not use the target to resolve the addresses but the endpoints but we can not enforce such relationship so I think that if one wants to use its own resolver it should do it by providing is own `channel builder`` so that it can also change the ``target``.

**Comment by fanminshi** [comment]
@lburgazzoli oh my bad. now I see what you meant.  the current`setEndpoint` only associates with `SimpleNameResolver` and `DnsSRVNameResolver` but not any `CustomNameResolverFactory`.

any `CustomNameResolver` would have `target` set to `"etcd"` which might not be what user wants; hence can be confusing.

removing NameResolver option make sense to me.

**Comment by fanminshi** [comment]
close via #181
