### ISSUE TITLE
Discuss wrap vs enhance

### ISSUE THREAD

**Issue by jhspaybar** [coreos/jetcd#18]
I see the EtcdKV interface and impl are wrapping the generated gRPC clients with some helper utilities.  At least for simple things like put and delete, I'd like to discuss if these should wrap, or sit to the side?  For example.

generatedClient.put(EtcdUtil.putRequest(key, value));

This way users can still easily choose their interaction model(blocking, future, async), but still get the benefit of a nicer builder and handy defaults.

I expect there to be recipes as well for common multi-step interactions, and those very well may need to wrap, but the items so far seem capable of living to the side as helpers.

Thoughts?

**Comment by xiang90** [comment]
@jhspaybar I think we want to hide gRPC details as much as possible to start with. Client lib should support blocking and nonblocking. The utility func should exist, it is just a question that if we should expose them to start with. Then users now only have one way to do the thing, and we can iterate on it until we know the API is stable and flexible. We might reach to a point that some users still want raw gRPC, but I want to start the discussion when we get there.

**Comment by fanminshi** [comment]
not relevant anymore.
