### ISSUE TITLE
pom: should add FindBugs static analysis to jetcd

### ISSUE THREAD

**Issue by fanminshi** [coreos/jetcd#182]
It seems to me a lot of java projects includes FindBugs maven plugin to help developer finding potential bugs. We probably should add that to Jetcd too.

http://findbugs.sourceforge.net/

**Comment by lburgazzoli** [comment]
Maybe we can use http://errorprone.info, not sure which one is the best but we try them

**Comment by fanminshi** [comment]
sounds good. close in favor of https://github.com/coreos/jetcd/issues/83
