### ISSUE TITLE
in memory caching using etcd4j #154

### ISSUE THREAD

**Issue by naveenkumargp** [coreos/jetcd#184]
Hi All,
i want to store the etcd data into the local cache using this etcd4j i e i want cache the etcd data using this etcd client code .is it possible to do with this present code if not how do we change the code .
can any one help to how to do this.
Regards
Naveen

**Comment by heyitsanthony** [comment]
@naveenkumargp have you tried the etcd [grpcproxy](https://github.com/coreos/etcd/blob/master/Documentation/op-guide/grpc_proxy.md)? it does just that

**Comment by xiang90** [comment]
also the name of the project is actually jetcd, not etcd4j :P. Try grpcProxy instead as @heyitsanthony mentioned.
