### ISSUE TITLE
discuss: jetcd  0.0.1 release

### ISSUE THREAD

**Issue by fanminshi** [coreos/jetcd#193]
I want to discuss what's needed be done for jetcd 0.0.1 release? Maven Central? Github Release? Uber Jar somewhere? and etc?

cc/ @lburgazzoli

**Comment by lburgazzoli** [comment]
I'd go for:

- maven central 
- oss sonattype for snapshots 
- ship an additional uber jar with shaded dependencies

**Comment by fanminshi** [comment]
@lburgazzoli good suggestions. Let's do that for 0.0.1 release.

**Comment by lburgazzoli** [comment]
We should ask to have an account on oss sonatype, do we have it ?

**Comment by fanminshi** [comment]
we don't have an account. I am following this guide to create an account. http://central.sonatype.org/pages/ossrh-guide.html.

**Comment by akd31** [comment]
Did you deploy this ?

Could not find artifact com.coreos:jetcd-core:jar:0.0.1 in oss-sonatype (https://oss.sonatype.org/content/repositories/snapshots/)

I get an error like this ?

**Comment by fanminshi** [comment]
@akd31 plan to deploy today.

**Comment by fanminshi** [comment]
@lburgazzoli when calling ` mvn clean package -P release`, jetcd-all only has jetcd-all.0.0.1.jar but doesn't include jetcd-all.0.0.1.-javadoc.jar. This is causing uploading artifacts to staging repo to fail due to "Missing: no javadoc jar found in folder `/com/coreos/jetcd-all/0.0.1`.

**Comment by fanminshi** [comment]
@lburgazzoli generating java-all jar with java doc is blocking 0.0.1 release it's a requirement for deploying to the maven central. I am not going to upload java-all 0.0.1 for now. We can try to deploy java-all independently or for next release.

**Comment by fanminshi** [comment]
@akd31 jetcd-core-0.0.1 is in maven central.
https://search.maven.org/#search%7Cga%7C1%7Ccoreos

**Comment by akd31** [comment]
Thank you 👍

**Comment by xiang90** [comment]
this is done. closing.
