### ISSUE TITLE
discuss: client builder 

### ISSUE THREAD

**Issue by lburgazzoli** [coreos/jetcd#195]
As today the ClientBuilder use bean style to set options like:

```java
ClientBuilder setEndpoints(List<String> ....)
List<String> getEndpoints(...)
```

But builders usually have a shorten and less verbose syntax:

```java 
ClientBuilder endpoints(List<String> ...)
List<String> endpoints(...)
```

See [ManagedChannelBuilder](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/ManagedChannelBuilder.java) for refeence.

In addition - as endpoints are mandatory -  it maybe better to have:

```java
ClientBuilder ClientBuilder.forEndpoints(...)
```

Instead of:

```java
ClientBuilder.newBuilder()
```

I'd also deprecate the possibility to set a custom channel builder as it may clash with the maintenance stuffs.

**Comment by fanminshi** [comment]
@lburgazzoli agreed. let's follow the `ManagedChannelBuilder` style. Do we still keep getter `get***()`?

**Comment by lburgazzoli** [comment]
``get*()`` just pollute the class so I'd get rid of them
