### ISSUE TITLE
github: enable advanced PR merge functionalities

### ISSUE THREAD

**Issue by lburgazzoli** [coreos/jetcd#205]
Beside basic merge options there are also:
- squash and merge
- rebase an merge

The later is the most interesting one to as allows to avoid the merge commit. would it make sense to enable it ?

**Comment by fanminshi** [comment]
@lburgazzoli I am curious what's the benefit of basic merge option vs rebase on merge. It seems to me that rebase an merge creates cleaner history avoiding additional merge commit e.g `Merge pull request #210 from fanminshi/improve_read_me`.

**Comment by lburgazzoli** [comment]
Yes, plain merge add a merge commit which pollute the log. Rebase make history cleaner.

**Comment by fanminshi** [comment]
@lburgazzoli I enabled the rebase on merge options.
