### ISSUE TITLE
failed to resolve name error occrued

### ISSUE THREAD

**Issue by shuijing198799** [coreos/jetcd#206]
I have add my etcd endpoints into a array and I try to telnet these endpoints, all are successed
moreover, when this code can be accepted 
Client client = ClientBuilder.newBuilder().setEndpoints(endPointList).build();

however when my process try to connect etcd , this error shows:

**2017-08-10 22:58:24  [ grpc-default-executor-0:1 ] - [ WARN ] com.coreos.jetcd.resolver.SmartNameResolver.doResolve(SmartNameResolver.java:118) Error wile getting list of servers
com.coreos.jetcd.exception.EtcdException
        at com.coreos.jetcd.exception.EtcdExceptionFactory.newEtcdException(EtcdExceptionFactory.java:9)
        at com.coreos.jetcd.exception.EtcdExceptionFactory.newEtcdException(EtcdExceptionFactory.java:13)
        at com.coreos.jetcd.resolver.SmartNameResolver.doResolve(SmartNameResolver.java:111)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Unable to resolve endpoints [http://192.168.1.45:2379, http://192.168.3.30:2379, http://192.168.1.48:2379]
        ... 4 more
Aug 10, 2017 10:58:24 PM io.grpc.internal.ManagedChannelImpl$NameResolverListenerImpl onError
WARNING: [io.grpc.internal.ManagedChannelImpl-1] Failed to resolve name. status=Status{code=NOT_FOUND, description=null, cause=null}**

it seems the http://192.168.1.45:2379 http://192.168.3.30:2379  http://192.168.1.48:2379 can't be resolve. why?

**Comment by lburgazzoli** [comment]
Looks strange, can you provide the full code ?

**Comment by shuijing198799** [comment]
@lburgazzoli of course
        try {
            String path = "/home/kptech/etcd/etcdendpoints";
            File file = new File(path);
            InputStream inputStream = new FileInputStream(file);
            byte bytes[]=new byte[(int)file.length()];
            inputStream.read(bytes, 0, bytes.length);
            inputStream.close();
            String endpoints =  new String(bytes);
            String[] endPointList = endpoints.replace("\n","").split(" ");
            for(int i = 0; i < endPointList.length; i++) {
                endPointList[i] = "http://" + endPointList[i];
                System.out.println(String.format("by jony %s",endPointList[i]));
            }   
            Client client = ClientBuilder.newBuilder().setEndpoints(endPointList).build();
            Watch watchClient = client.getWatchClient();
            return watchClient;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }   

this is the code initialize the client

and in the file 
/home/kptech/etcd/etcdendpoints
it write like this:
192.168.1.45:2379 192.168.3.30:2379 192.168.1.48:2379

and when the program run this code 
Watcher watcher = watchClient.watch(ByteSequence.fromString(whiteListKey));

this error occurs!

**Comment by lburgazzoli** [comment]
Sorry, can you test with the latest source ? There was a bug with the service loader so the resolver was unable to load resolvers for protocols.

**Comment by shuijing198799** [comment]
@lburgazzoli OK, let me have a try. thanks for your help,In chinese there is nearly 0 o'clock ,can I give you a feedback tomorrow?

**Comment by shuijing198799** [comment]
@lburgazzoli sorry, how can I get the latest version? I only find and build the jetcd-0.1.0-SNAPSHOT.jar.

**Comment by lburgazzoli** [comment]
you need to build it from sources

**Comment by shuijing198799** [comment]
@lburgazzoli 
this is my workflow 
I download the source code
git clone https://github.com/coreos/jetcd.git

and then I build it 
./mvnw install -Dmaven.test.skip=true

and then I can locate the jar in
/root/bootstrap/cluster/kpdev/lib/jetcd-0.1.0-SNAPSHOT.jar

is that right?

I rarely use java, So this question seems stupid , sorry.

**Comment by fanminshi** [comment]
@shuijing198799 once you git clone jetcd. you need to update the local repo with the upstream. then you build the jar with the latest master.

**Comment by fanminshi** [comment]
@shuijing198799 also your workflow is correct. you just need to make sure that the local repo is updated with the upstream one https://github.com/coreos/jetcd.git.

**Comment by shuijing198799** [comment]
@fanminshi I feel asleep on sofa . sorry. thanks for your help ,I try to fix it now.

**Comment by fanminshi** [comment]
@shuijing198799 is the issue fixed with latest master?

**Comment by shuijing198799** [comment]
@fanminshi  @lburgazzoli  thx for resolve my problem. I have fixed it.
