### ISSUE TITLE
Cluster connection problems

### ISSUE THREAD

**Issue by f4n** [coreos/jetcd#208]
Hi, i have two problems with the attached sample cluster application and i hope that somebody has an idea what the problem is.

If all three processes are up, everything works fine.
If i kill the first process (2379) i would expect the KVClient quietly switch to the next address from the connection list but it doesn't. i get an exception `UNAVAILABLE: etcdserver: request timed out`. Is there any way to use such failover mechanism? Or what's the idea behind the connection list?
Interesting remark: the ClusterClient is still able to resolve the members in the cluster.

The second strange thing is the ClusterClient. I have 3 etcd processes but the client resolves 4, 3 valid etcd server names and one with an empty string like:
```
Members: 4
Member name: etcd2
Member name: etcd0
Member name: 
Member name: etcd1
```
Is the empty member the demo app connection?

Demo App:
```java
Client client = Client.builder().endpoints("http://localhost:2379", 
   "http://localhost:2479", "http://localhost:2579").build();

Cluster clusterClient = client.getClusterClient();
try {
  MemberListResponse cresponse = clusterClient.listMember().get();
  System.out.println("Members: " + cresponse.getMembers().size());
  for( Member m : cresponse.getMembers() ) {
    System.out.println("Member name: " + m.getName());
  }
} catch (InterruptedException | ExecutionException e3) {
  e3.printStackTrace();
}

KV kvClient = client.getKVClient();

ByteSequence key = ByteSequence.fromString("foo");
ByteSequence value = ByteSequence.fromString("bar");

try {
  kvClient.put(key, value).get();
} catch (InterruptedException | ExecutionException e1) {
  e1.printStackTrace();
}
```

**Comment by lburgazzoli** [comment]
For the first issue, as far as I can remember killing a node of the cluster may lead to the cluster to be in an inconsistent state and you should get the same result if you use etcdctl.

**Comment by f4n** [comment]
Yes you are right, i got the same with etcdctl. Did i configure something wrong or is there no failover in etcd?

```
/ # etcdctl -C http://localhost:2379,http://localhost:2479,http://localhost:2579 set foo bar2
Error:  client: etcd cluster is unavailable or misconfigured; error #0: client: endpoint http://localhost:2479 exceeded header timeout
; error #1: dial tcp [::1]:2379: getsockopt: connection refused
; error #2: client: endpoint http://localhost:2579 exceeded header timeout

error #0: client: endpoint http://localhost:2479 exceeded header timeout
error #1: dial tcp [::1]:2379: getsockopt: connection refused
error #2: client: endpoint http://localhost:2579 exceeded header timeout

/ # etcdctl -C http://localhost:2379,http://localhost:2479,http://localhost:2579 cluster-health
member 744924ed0b37b9b1 is unhealthy: got unhealthy result from http://localhost:2579
failed to check the health of member 77fb14b13d7590f7 on http://localhost:2379: Get http://localhost:2379/health: dial tcp [::1]:2379: getsockopt: connection refused
member 77fb14b13d7590f7 is unreachable: [http://localhost:2379] are all unreachable
member 857fbccbc239f483 is unreachable: no available published client urls
member e1110983ed7857fe is unhealthy: got unhealthy result from http://localhost:2479
cluster is unhealthy
```

**Comment by fanminshi** [comment]
@f4n how are you creating etcd cluster?

```
Members: 4
Member name: etcd2
Member name: etcd0
Member name: 
Member name: etcd1
```
I am unsure how you have 4 members if you only configure 3.

**Comment by fanminshi** [comment]
@f4n it seems like this is an etcd issue. please file the issue to etcd repo, https://github.com/coreos/etcd.

**Comment by f4n** [comment]
It was a misconfiguration/old data of my cluster. I removed all the data and restarted it with --initial-cluster-state new, now everything works fine. Thank you
