### ISSUE TITLE
watch: Watcher.listen() should have an overloaded parameter with timeout

### ISSUE THREAD

**Issue by lburgazzoli** [coreos/jetcd#215]
Watcher.listen() waits in-definitively so it would be nice to have an overloaded method that allow to set a timeout, like

```java
watcher.listen(5, TimeUnits.SECONDS);
```

**Comment by fanminshi** [comment]
@lburgazzoli let's see if more users want this. then we can add it. I think if we use`watcher.close() ` combines with extra thread that waits. then that should have same effect as timeout.

**Comment by lburgazzoli** [comment]
Closing it as I'm going to implement an sync watcher
