### ISSUE TITLE
How can I get the sample code contain the HTTPS

### ISSUE THREAD

**Issue by yangliucheng** [coreos/jetcd#232]
I use code as follow to create a client support https:
`Client.builder().endpoints(endpoints).sslContext(context).build();`
but I do not know how to complete code of 'context'

**Comment by yangliucheng** [comment]
https://github.com/grpc/grpc-java/blob/master/interop-testing/src/test/java/io/grpc/testing/integration/TlsTest.java    

this sample does not work very well.

**Comment by yangliucheng** [comment]
`String ca = "D:\\kubernetes\\ca.cer";
String cert = "D:\\kubernetes\\server.cer";
String key = "D:\\kubernetes\\server_key_decode.pem";`

**Comment by fanminshi** [comment]
@yangliucheng taking a look.

**Comment by fanminshi** [comment]
cc/ @skyao @俊雄 could you guys take a look of setting up tls for jetcd.

**Comment by fanminshi** [comment]
@yangliucheng fixed via https://github.com/coreos/jetcd/issues/162
