### ISSUE TITLE
client: uses java.lang.AutoCloseable

### ISSUE THREAD

**Issue by ScienJus** [coreos/jetcd#239]
Make `com.coreos.jetcd.Client` and `com.coreos.jetcd.internal.impl.CloseableClient` extends `java.lang.AutoCloseable`, then we can use Client with `try-with-resource` like:

```
try (Client client = Client.builder().endpoints("http://127.0.0.1:2379").build();
     KV kv = client.getKVClient()) {
  System.out.println(kv.get(ByteSequence.fromString(key)));
}
```

and it's useful when client is a spring bean.

**Comment by fanminshi** [comment]
@lburgazzoli what's your opinion about this?

**Comment by lburgazzoli** [comment]
I agree, auto closeable would be useful

**Comment by fanminshi** [comment]
@ScienJus let's support this then.
