### ISSUE TITLE
Support of lock API

### ISSUE THREAD

**Issue by fomkin** [coreos/jetcd#246]
Cant it be implemented?

https://github.com/coreos/etcd/blob/master/Documentation/dev-guide/api_concurrency_reference_v3.md#service-lock-etcdserverapiv3lockv3lockpbv3lockproto

**Comment by Grisu118** [comment]
I'm currently working on a PR for this, because we need it too.

https://github.com/Grisu118/jetcd/tree/GG-489-add-lock-support

**Comment by xiang90** [comment]
@Grisu118 

Thanks!
