### ISSUE TITLE
Name resolving seems overcomplicated

### ISSUE THREAD

**Issue by gtudan** [coreos/jetcd#249]
The `SmartNameResolver` uses the Java ServiceLoader to lookup implementations of `URIResolver`. I would like to understand why this design decision was made, as it seems a little overengineered. The implementations are right there in the same package. Is there a use case for implementing your own resolver?

I tripped over this one when I tried started implementing a JCA-Resource-Adapter based on this library. Classloading in Application Servers can be quiet messy and the service loader caught me off guard.

If you had a use-case for this in mind then I'm fine with the service loader - but could we default to the build-in ones in case the service-loader fails to resolve them?

**Comment by lburgazzoli** [comment]
The initial idea was to move additional resolvers like dns-srv out of the core package that's why we have the service loader now but this is not the final version as we have also to deal with OSGi so cassloading is definitively an issue.

I'll try to make it simple and flexible in the coming days.

**Comment by lburgazzoli** [comment]
It should be fixed by #250
