### ISSUE TITLE
dns discovery

### ISSUE THREAD

**Issue by lburgazzoli** [coreos/jetcd#25]
In @jurmous etcd4j's client, there were a simple dns srv discovery util to get a list of etcd instances, would it make sense to port it here ?

**Comment by AdoHe** [comment]
@lburgazzoli thanks for pointing out this, I will take a look, if possible I will port it here, and actually we are going to implement one, you can see [here](https://github.com/coreos/jetcd/blob/master/src/main/java/com/coreos/jetcd/lb/EtcdNameResolverFactory.java). Thx :)

**Comment by lburgazzoli** [comment]
@AdoHe best would be to have a common class to extend then I could el providing a dns imp

**Comment by AdoHe** [comment]
@lburgazzoli grpc-java already has a dns based name resolver provider, I guess you are trying to implement a different one. So I would add an `AbstractEtcdNameResolverFactory` class, then you could provide a dns impl.

**Comment by lburgazzoli** [comment]
I had a quick look at grpc's dns impl but it does not seems to use srv records. 
I would like to be able to leverage etcd or discovery options [1][2] like:

- dns:
```java
EtcdClientBuilder.newBuilder()
    .endpoints("dns+srv://_etcd-server._tcp.example.com")
    ...
```

- etcd: 
```java
EtcdClientBuilder.newBuilder()
    .endpoints("etcd://discovery.etcd.io/3e86b59982e49066c5d813af1c2e2579cbf573de")
    ...
```

If it make sese of course.


[1] https://coreos.com/etcd/docs/latest/clustering.html#etcd-discovery
[2] https://coreos.com/etcd/docs/latest/clustering.html#dns-discovery

**Comment by AdoHe** [comment]
@lburgazzoli so I would suppose there are three ways to specify the endpoints:

1. dns:
```
EtcdClientBuilder.newBuilder()
    .endpoints("dns+srv://_etcd-server._tcp.example.com")
    ...
```
2. etcd discovery:
```
EtcdClientBuilder.newBuilder()
    .endpoints("etcd://discovery.etcd.io/3e86b59982e49066c5d813af1c2e2579cbf573de")
    ...
```
3. plain host:port list:
```
EtcdClientBuilder.newBuilder()
    .endpoints("http://10.0.0.1:2379", "http://10.0.0.2:2379")
    ...
```
Then we need to implement three types name resolver. wdyt?

**Comment by lburgazzoli** [comment]
Could be, I do not yet know how the name resolver work but it is definitively be required for srv and etcd.

**Comment by AdoHe** [comment]
@lburgazzoli I opened an init pr #26, ptal.

**Comment by AdoHe** [comment]
@lburgazzoli I would think dns based name resolver will resolve SRV records found at specific DNS domain name, discovery based name resolver will fetch discovery service to get endpoint addresses, directly host:port will just use user configured list of endpoints.

**Comment by AdoHe** [comment]
Also the `AbstractEtcdNameResolverFactory` may be not complete, we may add more methods here.

**Comment by AdoHe** [comment]
@lburgazzoli this pr #26 has merge, would you help implement dns based name resolver? Thanks very much :)

**Comment by lburgazzoli** [comment]
@AdoHe I will

**Comment by lburgazzoli** [comment]
@AdoHe I see that in grpc-java they use NameResolverProvider instead of NameResolver.Factory , which one should we use ?

**Comment by AdoHe** [comment]
@lburgazzoli we should use `NameResolver.Factory`, `ManagedChannelBuilder` can configure this.

**Comment by lburgazzoli** [comment]
I've created PR #31 for discussion, let me know what your opinion is
