### ISSUE TITLE
does this etcd client support https?

### ISSUE THREAD

**Issue by davidstack** [coreos/jetcd#251]
does this etcd client support https? could give a example of using https to connect etcd? thanks

**Comment by shveik** [comment]
there was an example added a few days ago in the master branch that showed how to use it with localhost. Unfortunately, some details were missing. The client process has to be started with 
-Xbootclasspath/p:/<path-to-jar>/alpn-boot-8.1.10.v20161026.jar or some configuration specific to a web server.
Also, I am having trouble authenticating against a remove server (not localhost) with exception: 
```
CertificateException No subject alternative DNS name matching <authority here> found.  sun.security.util.HostnameChecker.matchDNS (HostnameChecker.java:204)
```
so, if anyone can validate that the new code can talk to a remote server, it would go a long way in the new build. @lburgazzoli 

I maybe incorrect in my assumptions about how to use the code, so I am happy to test further. 

Thanks!

**Comment by lburgazzoli** [comment]
The test provided is a very simple an minimalist ssl setup, but jetcd relies on grpc-java and netty so relevant information about ssl can be found here:

- https://github.com/grpc/grpc-java/blob/master/SECURITY.md


About the error you are facing, tou need to set a proper authority as done in the example here: 

- https://github.com/coreos/jetcd/blob/master/jetcd-core/src/test/java/com/coreos/jetcd/internal/impl/SslTest.java#L46

**Comment by shveik** [comment]
how does the authority work with self-signed certs?

**Comment by shveik** [comment]
i also think that the tests are working because the servers are run on localhost.

**Comment by davidstack** [comment]
@lburgazzoli  i try to use the SslTest.java example,but it failed,because the authority method does not exist in com.coreos:jetcd-core:0.0.1.

**Comment by shveik** [comment]
@davidstack you need to build from source, the authority method is not yet released.

**Comment by davidstack** [comment]
@shveik  thanks

**Comment by lburgazzoli** [comment]
@shveik can we close this ?
