### ISSUE TITLE
Cannot maven build sample `jetcd-simple-ctl`

### ISSUE THREAD

**Issue by namgivu** [coreos/jetcd#254]
I'm trying the sample code [here](https://github.com/coreos/jetcd/tree/master/jetcd-examples/jetcd-simple-ctl) and cannot get the first step succeed i.e. `./mvnw clean package` failed.

Error as the snapshot. 
How to get around that?
Regards,
Nam

![screenshot from 2017-10-24 10-49-12](https://user-images.githubusercontent.com/1185192/31924142-6fa054c8-b8a9-11e7-90b4-18e0482aff3c.png)

**Comment by lburgazzoli** [comment]
As it uses the SNAPSHOT version, you should build at least jetcd-core first
