### ISSUE TITLE
Maven build failed

### ISSUE THREAD

**Issue by namgivu** [coreos/jetcd#255]
I'm trying the sample code [here](https://github.com/coreos/jetcd/tree/master/jetcd-examples/jetcd-simple-ctl) and cannot get the first step succeed i.e. `./mvnw clean package` failed.

Error as the snapshot. 
How to get around that?
Regards,
Nam

![screenshot from 2017-10-24 10-49-12](https://user-images.githubusercontent.com/1185192/31924142-6fa054c8-b8a9-11e7-90b4-18e0482aff3c.png)

**Comment by lburgazzoli** [comment]
Looks the same as #254  you should first install jetcd-core at least

**Comment by namgivu** [comment]
Hi @lburgazzoli,
I expect the maven to install that for the sample code. 
Or I may misunderstand maven usage here?
Nam

**Comment by lburgazzoli** [comment]
It does if the version required is available from on a maven repository but jetcd 0.1.0-SNAPSHOT is not so you need to install it from sources.
