### ISSUE TITLE
Publish SNAPSHOTs

### ISSUE THREAD

**Issue by lburgazzoli** [coreos/jetcd#257]
We should publish snapshots for each successful build of master branch on travis-ci so people can try the lastest code without building it from source.

**Comment by fanminshi** [comment]
yeah, we should do that. Does snapshot needs to be signed with pgp key?

**Comment by lburgazzoli** [comment]
not afaik

**Comment by fanminshi** [comment]
@lburgazzoli sounds good.

**Comment by adprocas** [comment]
I would like to third this opinion.

**Comment by fanminshi** [comment]
@lburgazzoli I am working on this but unsure what is the best way to support. any suggestions? I am currently looking at this plugin https://github.com/egineering-llc/gitflow-helper-maven-plugin

**Comment by fanminshi** [comment]
I am able to publish snapshot for `jetcd`, `jetcd-core`, and `jetcd-discovery-dns-srv` but not `jetcd-watch-example`.
```sh
$mvn deploy -DskipTests=true
...
INFO] --- maven-deploy-plugin:2.7:deploy (default-deploy) @ jetcd-watch-example ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] jetcd .............................................. SUCCESS [  3.345 s]
[INFO] jetcd-core ......................................... SUCCESS [ 26.028 s]
[INFO] jetcd-discovery-dns-srv ............................ SUCCESS [  3.483 s]
[INFO] jetcd-watch-example ................................ FAILURE [  0.370 s]
[INFO] jetcd-simple-ctl ................................... SKIPPED
[INFO] jetcd-examples ..................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 34.170 s
[INFO] Finished at: 2018-02-13T15:34:51-08:00
[INFO] Final Memory: 91M/356M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project jetcd-watch-example: Deployment failed: repository element was not specified in the POM inside distributionManagement element or in -DaltDeploymentRepository=id::layout::url parameter -> [Help 1]
```

Investigating on how to skip `jetcd-watch-example`
cc/ @lburgazzoli any idea?

**Comment by lburgazzoli** [comment]
I guess we can add something like:

```xml
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-deploy-plugin</artifactId>
  <version>X.Y</version>
  <configuration>
    <skip>true</skip>
  </configuration>
</plugin>
```

To modules we do not want to deploy

**Comment by fanminshi** [comment]
I pushed the snapshot manually.

**Comment by lburgazzoli** [comment]
@fanminshi if you grant me access to com.coreos on sonatype I can work on automatically release snapshots on every successful pr (on master), my user name on sonatype is lburgazzoli. Maybe I also need some permissions on travis-ci to edit project configuration.

**Comment by fanminshi** [comment]
@lburgazzoli  let me take a look in  granting you access to com.coreos on sonatype.

**Comment by fanminshi** [comment]
@lburgazzoli I am using Nexus Repository Manager 2.14.8-01 from https://oss.sonatype.org/. I don't see an option to add more user. Any idea why?

**Comment by fanminshi** [comment]
@lburgazzoli I am curious how are you able to publish the snapshot without me adding you as a user?

**Comment by lburgazzoli** [comment]
as I am a maintainer, I've asked sonatype to grant me the permission to do so :)

**Comment by fanminshi** [comment]
@lburgazzoli awesome!!
