### ISSUE TITLE
ServiceLoader prevents jetcd from working in Karaf

### ISSUE THREAD

**Issue by jeethridge** [coreos/jetcd#262]
I'm trying to get jetcd working in a poject that runs in Karaf. I'm currently working primarily with the 0.0.1 build and I'm hoping somebody can help me out. Basically, in Karaf, the jetcd client can't resolve any hostnames. This is due to the call to ServiceLoader.load(URIResolver.class) in SmartNameResolver.java. My understanding is that it is possible to work around this in karaf by modifying the MANIFEST.MF file in the jetcd-core-0.0.1.jar file. The goal is to tell Karaf that it needs to use the SPI-Fly module to dynamically load the URIResolver implementations by temporarily using a classloader in a different context. 

I've made the following change to the manifest:

Require-Capability:osgi.serviceloader;filter:="(osgi.serviceloader=com.coreos.jetcd.resolver.URIResolver)";resolution:=optional;cardinality:=multiple,osgi.extender;filter:="(osgi.extender=osgi.serviceloader.processor)"osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"

I've also tried this to see if I could get it to use just the Direct name resolver.

Require-Capability:osgi.serviceloader;filter:="(osgi.serviceloader=com.coreos.jetcd.resolver.URIResolvers$Direct)";resolution:=optional;cardinality:=multiple,osgi.extender;filter:="(osgi.extender=osgi.serviceloader.processor)"osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"

 So far I've had no luck and a continue to get the same error in karaf:

2017-12-06 11:09:42,611 | WARN  | fault-executor-0 | SmartNameResolver                | 56 - com.foo.jetcd.example - 1.0.0.SNAPSHOT | Error wile getting list of servers
com.coreos.jetcd.exception.EtcdException: Unable to resolve endpoints [http://0.0.0.0:2379]
        at com.coreos.jetcd.exception.EtcdExceptionFactory.newEtcdException(EtcdExceptionFactory.java:30)
        at com.coreos.jetcd.resolver.SmartNameResolver.doResolve(SmartNameResolver.java:135)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)[:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)[:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748)[:1.8.0_151]
2017-12-06 11:09:42,614 | WARN  | fault-executor-0 | ManagedChannelImpl               | 56 - com.foo.jetcd.example - 1.0.0.SNAPSHOT | [io.grpc.internal.ManagedChannelImpl-1] Failed to resolve name. status=Status{code=NOT_FOUND, description=null, cause=null}
2017-12-06 11:09:42,617 | ERROR | nsole user karaf | example                          | 56 - com.foo.jetcd.example - 1.0.0.SNAPSHOT | [com.foo.jetcd.example.JetcdClient(1)] The start method has thrown an exception
java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: NOT_FOUND

I'm wondering if anyone has been able to get around this issue. Also, if so, I'd like to suggest updating the configuration of the maven-bundle-plugin so that this works out of the box. If somebody can help me figure out what the manifest should look like I'd be happy to submit a PR with the changes to the maven-bundle-plugin configuration.

**Comment by lburgazzoli** [comment]
The latests source should not expose this problem at least the direct resolver is available out of the box. I will work on OSGi stuffs as soon as I have time but could you please check the latest code does not have the same problem ?

**Comment by jeethridge** [comment]
Sure, I'll try building from the latest source and let you know what I run into. I know for this version we also had to work around a ClassNotFoundError because of a split package issue between grpc-context and grpc-core, but that may not be something you have a lot of control over.

**Comment by jeethridge** [comment]
@lburgazzoli I think I've managed to get it working by building the latest jetcd-core-0.1.0-SNAPSHOT.jar, however, it's somewhat based on trial and error with the other dependencies we've included. In order to get it to install and run properly, we have the following dependencies declared in the pom.xml in our project: 

    <dependencies>
        
        <dependency>
            <groupId>com.coreos</groupId>
            <artifactId>jetcd-core</artifactId>
            <version>0.1.0-SNAPSHOT</version>
        </dependency>
        
        <dependency>
            <groupId>com.google.protobuf.nano</groupId>
            <artifactId>protobuf-javanano</artifactId>
            <version>3.1.0</version>
        </dependency>
        <dependency>
            <groupId>com.jcraft</groupId>
            <artifactId>jzlib</artifactId>
            <version>1.1.3</version>
        </dependency>
        <dependency>
            <groupId>com.ning</groupId>
            <artifactId>compress-lzf</artifactId>
            <version>0.9.9</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-tcnative</artifactId>
            <version>2.0.0.Final</version>
        </dependency>
        <dependency>
            <groupId>com.github.jponge</groupId>
            <artifactId>lzma-java</artifactId>
            <version>1.3</version>
        </dependency>
        <dependency>
            <groupId>net.jpountz.lz4</groupId>
            <artifactId>lz4</artifactId>
            <version>1.3.0</version>
        </dependency>
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk16</artifactId>
            <version>1.46</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty.alpn</groupId>
            <artifactId>alpn-api</artifactId>
            <version>1.1.3.v20160715</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.25</version>
            <scope>provided</scope>
        </dependency>

        
        <dependency>
            <groupId>org.osgi</groupId>
            <artifactId>org.osgi.service.component</artifactId>
            <version>1.3.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.osgi</groupId>
            <artifactId>org.osgi.core</artifactId>
            <version>6.0.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.osgi</groupId>
            <artifactId>org.osgi.service.cm</artifactId>
            <version>1.5.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.osgi</groupId>
            <artifactId>org.osgi.service.component.annotations</artifactId>
            <version>1.3.0</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

You wouldn't be able to advise on a simpler / more correct set of dependencies that would accomplish the same goal, would you?

**Comment by lburgazzoli** [comment]
I'll try to provide a karaf featurex xml for the next release but I'm quite busy so I do not have an ETA so if you have any spare time to work on that I'd more than happy to review and merge a PR.

**Comment by jeethridge** [comment]
Understood. It looks like the latest snapshot is the path forward for us, so If I can get something working cleanly I'll submit a PR.
