### ISSUE TITLE
Get Query for Retrieving all Keys

### ISSUE THREAD

**Issue by indrabasak** [coreos/jetcd#266]
What is the equivalent KV client query for performing the following operation to retrieve all keys?

```
etcdctl get "" --prefix=true
```
I tried the following query, it didn't work.
```
 CompletableFuture<GetResponse> futureResponse =
      client.getKVClient().get(ByteSequence.fromString(""),
          GetOption.newBuilder().withPrefix(ByteSequence.fromString("true")).build());

 GetResponse response = futureResponse.get();
```

**Comment by sampowers** [comment]
etcdctl (in v3 mode) appears to be special-casing the empty string arg for getPrefix as `0x00` then using WithFromKey instead of WithPrefix.  I see you are using withPrefix.

jetcd has `withRange` which I am guessing is equivalent to WithFromKey in etcdctl.

So for the jetcd equivalent, try using withRange(\0).

See https://github.com/coreos/jetcd/blob/112956b907e7ea09fd5daf4e40dd99cf3f27dd0e/jetcd-core/src/main/java/com/coreos/jetcd/options/GetOption.java#L140

**Comment by indrabasak** [comment]
It did the trick. Thanks, Sam!

**Comment by xiang90** [comment]
we probably need to document this somewhere, or provide a const to make it clear.

**Comment by timchenxiaoyu** [comment]
how to use withRange ?

**Comment by indrabasak** [comment]
[Here](https://github.com/indrabasak/spring-etcd-example/blob/master/src/main/java/com/basaki/data/repository/BookRepositoryImpl.java) is a complete example using `withRange`:

    @Override
    public Map<String, String> findAllKeys() {
        try {
            ByteSequence key = ByteSequence.fromString("\0");
            GetOption option = GetOption.newBuilder()
                    .withSortField(GetOption.SortTarget.KEY)
                    .withSortOrder(GetOption.SortOrder.DESCEND)
                    .withRange(key)
                    .build();

            CompletableFuture<GetResponse> futureResponse =
                    client.getKVClient().get(key, option);

            GetResponse response = futureResponse.get();
            if (response.getKvs().isEmpty()) {
                log.info("Failed to retrieve any keys.");
                return null;
            }


            Map<String, String> keyValueMap = new HashMap<>();
            for (KeyValue kv : response.getKvs()) {
                keyValueMap.put(kv.getKey().toStringUtf8(),
                        kv.getValue().toStringUtf8());
            }

            log.info("Retrieved " + response.getKvs().size() + " keys.");

            return keyValueMap;

        } catch (Exception e) {
            throw new DatabaseException(
                    "Failed to retrieve any keys.", e);
        }
    }

**Comment by timchenxiaoyu** [comment]
thks
