### ISSUE TITLE
run_etcd.sh has drifted from run_etcd_docker.sh

### ISSUE THREAD

**Issue by sampowers** [coreos/jetcd#267]
If the cluster is started up with the apparently older `run_etcd.sh`, it will not run the `etcd-ssl` or `etcd-proxy` processes, which are depended on by the maven tests.  So the tests fail when not using `run_etcd_docker.sh`.

I think they should be updated to match, or if `run_etcd.sh` is obsolete it should be removed.

**Comment by fanminshi** [comment]
@sampowers the tests should be run again run_etcd_docer.sh. I think `run_etcd.sh` can be removed. @lburgazzoli what do you think?

**Comment by sampowers** [comment]
@fanminshi I agree that removing run_etcd.sh would be one way to resolve the issue.  Needing docker to run the tests doesn't bother me, personally.

Is run_etcd.sh used by builds or other automated processes?   I didn't want to outright suggest removal without knowing if `run_etcd.sh` is needed by something.

**Comment by fanminshi** [comment]
@sampowers i think `run_etcd.sh` is used to testing originally. i don't think it is being used anywhere else. I need to double check on that.

**Comment by lburgazzoli** [comment]
afaik it is not needed anymore

**Comment by fanminshi** [comment]
@sampowers would you like to submit an pr to fix this and update the readme.md as well?
