### ISSUE TITLE
Watch a range of keys

### ISSUE THREAD

**Issue by nixgadget** [coreos/jetcd#268]
Its not very clear from the documentation but how do you watch for a range of keys ?
Say I have a map of keys and I want to iterate through these and watch every key for a certain time.

This seems to be possible with [`etcdctl`](https://github.com/coreos/etcd/blob/master/Documentation/dev-guide/interacting_v3.md#watch-key-changes)

Is this possible with v0.0.1 ?

**Comment by fanminshi** [comment]
@nixgadget this it is. you want to use  [`Watcher watch(ByteSequence key, WatchOption watchOption)`](https://github.com/coreos/jetcd/blob/master/jetcd-core/src/main/java/com/coreos/jetcd/Watch.java#L37`)

and use watchOption [`withRange(ByteSequence endKey)`](https://github.com/coreos/jetcd/blob/master/jetcd-core/src/main/java/com/coreos/jetcd/options/WatchOption.java#L81)

**Comment by fanminshi** [comment]
please reopen if you have more question.
