### ISSUE TITLE
SSL Not working

### ISSUE THREAD

**Issue by Abhijith1** [coreos/jetcd#271]
I'm trying to hit etcd with TLS. My `Client` looks something like this:

` client = Client.builder()
                .endpoints(etcdAddr)
                .user(ByteSequence.fromString(username))
                .password(ByteSequence.fromString(password))
            .sslContext(GrpcSslContexts.forClient()
                .trustManager(cert)
                .build())
                .build();`

But I keep getting the following error: `java.lang.IllegalArgumentException: Jetty ALPN/NPN has not been properly configured`.
`I'm using java version "1.8.0_152"`

**Comment by lburgazzoli** [comment]
Do you have a proper ssl implementation on the classpath ? see https://github.com/grpc/grpc-java/blob/master/SECURITY.md

**Comment by Abhijith1** [comment]
Yes, I've added `compile 'io.netty:netty-tcnative-boringssl-static:2.0.7.Final'` in my`dependencies`
I use gradle for dependancy management.

**Comment by Abhijith1** [comment]
@lburgazzoli Yes, I've added compile 'io.netty:netty-tcnative-boringssl-static:2.0.7.Final' in mydependencies
I use gradle for dependancy management.
My dependencies looks like this:
`dependencies {
    compile 'com.coreos:jetcd-core:0.0.1'
    compile 'org.slf4j:slf4j-simple:1.6.1'
    compile 'io.netty:netty-tcnative-boringssl-static:2.0.6.Final'
}`

**Comment by lburgazzoli** [comment]
Hard to tell, there is a test that uses ssl, can you check your example against that one ? You may also need to build jetcd form sources to use the latest bits.

**Comment by xiang90** [comment]
@Abhijith1 Why do you close it?

**Comment by Abhijith1** [comment]
@xiang90 @lburgazzoli Weirdly I tried running my code on a different machine and it worked. I re-installed java and tried it on my machine and I faced the same issue again. :( Could be an IDE issue as well. I use IntelliJ IDEA Version: 2017.3.2.

**Comment by lburgazzoli** [comment]
@Abhijith1 is sthi this an issue ?

**Comment by Abhijith1** [comment]
I got this sorted. There were other issues I ran into but I've got them resolved now. (Got the other issues sorted here: https://github.com/coreos/jetcd/issues/275)
