### ISSUE TITLE
Use jetcd put a k-v, why use etcdctl not find the value of the key

### ISSUE THREAD

**Issue by jinjiangxu** [coreos/jetcd#274]
java code：
Client client = Client.builder().endpoints("http://127.0.0.1:2379").build();
client.getKVClient().put(ByteSequence.fromString("/message"), ByteSequence.fromString("hello")).get();

./etcdctl get /message

**Comment by lburgazzoli** [comment]
Make sure to set environment variable ETCDCTL_API=3, see https://github.com/coreos/etcd/tree/master/etcdctl#etcdctl

**Comment by fanminshi** [comment]
@jinjiangxu has @lburgazzoli suggestion solve your issue?
