### ISSUE TITLE
package com.coreos.jetcd.api not exists

### ISSUE THREAD

**Issue by men348** [coreos/jetcd#277]
Why so many errors when I downlod the project and then compile it.
Error:(19, 28) java: package com.coreos.jetcd.api do not exists
like this:
public class UnlockResponse extends AbstractResponse<com.coreos.jetcd.api.lock.UnlockResponse> {

  public UnlockResponse(com.coreos.jetcd.api.lock.UnlockResponse response) {
    super(response, response.getHeader());
  }

}

public class AuthRoleAddResponse extends
    AbstractResponse<com.coreos.jetcd.api.AuthRoleAddResponse> {

  public AuthRoleAddResponse(com.coreos.jetcd.api.AuthRoleAddResponse response) {
    super(response, response.getHeader());
  }
}

public class AuthRoleGetResponse extends
    AbstractResponse<com.coreos.jetcd.api.AuthRoleGetResponse> {

  private List<Permission> permissions;

  public AuthRoleGetResponse(com.coreos.jetcd.api.AuthRoleGetResponse response) {
    super(response, response.getHeader());
  }

  private static Permission toPermission(com.coreos.jetcd.api.Permission perm) {
    ByteSequence key = ByteSequence.fromBytes(perm.getKey().toByteArray());
    ByteSequence rangeEnd = ByteSequence.fromBytes(perm.getRangeEnd().toByteArray());
    Permission.Type type;
    switch (perm.getPermType()) {
      case READ:
        type = Type.READ;
        break;
      case WRITE:
        type = Type.WRITE;
        break;
      case READWRITE:
        type = Type.READWRITE;
        break;
      default:
        type = Type.UNRECOGNIZED;
    }
    return new Permission(type, key, rangeEnd);
  }

  public synchronized List<Permission> getPermissions() {
    if (permissions == null) {
      permissions = getResponse().getPermList().stream()
          .map(AuthRoleGetResponse::toPermission)
          .collect(Collectors.toList());
    }

    return permissions;
  }
}

What‘s wrong????
![1516613218898](https://user-images.githubusercontent.com/17843929/35213831-f59c0036-ff99-11e7-8a24-ce3f871e5093.jpg)

**Comment by lburgazzoli** [comment]
what are you doing ?

**Comment by men348** [comment]
@lburgazzoli   I upload a image.

**Comment by lburgazzoli** [comment]
You need to compile protobuf files first, this is done my maven.

**Comment by fanminshi** [comment]
@men348 we don't check in protobuf file into the repo itself. you need to build those with maven first.

@lburgazzoli maybe we should have a doc on how to build the project locally?

**Comment by fanminshi** [comment]
@men348 are you able to build the project from source?

**Comment by fanminshi** [comment]
can be fixed `maven clean install`

**Comment by pdgetrf** [comment]
Still seeing this error in intellij. Any idea?

![image](https://user-images.githubusercontent.com/252020/50715555-b30e9f80-1032-11e9-88c0-12e2e2289b3c.png)
