### ISSUE TITLE
watch prefix change with depth control or regex in jetcd 0.0.1

### ISSUE THREAD

**Issue by zonghaishang** [coreos/jetcd#280]
I'm using jetcd (version 0.0.1), How to use api:
`client.Watch("\x02/servers/", clientv3.WithPrefix()) ;`
`client.Watch("\x03/servers/server-a/", clientv3.WithPrefix()) ?`
@heyitsanthony @xiang90 @yy2008
refer: https://github.com/coreos/etcd/issues/5402

**Comment by fanminshi** [comment]
@zonghaishang have you take a look of [Watcher watch(ByteSequence key, WatchOption watchOption)](https://github.com/coreos/jetcd/blob/master/jetcd-core/src/main/java/com/coreos/jetcd/Watch.java#L37) ?

**Comment by zonghaishang** [comment]
@fanminshi  I have tried , but no working.
Here is my test code:
``` java
  void watch(Client client) throws Exception {
    Watcher watcher = null;
    try {

       watcher = client.getWatchClient().watch(
                ByteSequence.fromString(key),
                WatchOption.newBuilder().withPrefix(
                        ByteSequence.fromString(key)
                ).build());

      long lease = client.getLeaseClient().grant(10).get().getID();

      client.getKVClient().put(ByteSequence.fromString("/servers/server-d")
      , ByteSequence.fromString(Long.toHexString(lease)),
              PutOption.newBuilder().withLeaseId(lease).build());

      new RefreshLease(client, lease, watcher).start();

      this.getClass().wait();

    } catch (Exception e) {
      if (watcher != null) {
        watcher.close();
      }
      throw e;
    }
  }
```

**Comment by fanminshi** [comment]
sorry for the delay. I am taking a look into this.

**Comment by fanminshi** [comment]
`I'm watching /servers/ & /servers/server-d/ with --prefix. if I put /servers/server-d/interface/helloworld,
I dont want got notified .`

This is the expected behavior since `/servers/server-d/interface/helloworld` has the prefix `/servers/server-d/`, then the wacher on `/servers/server-d/` will get notified.

**Comment by fanminshi** [comment]
@zonghaishang I took a look of etcd api agin. Currently, we don't support depth control natively. One way to support this feature is to wrap the watcher with prefix, and filter out the result that you don't want yourself.

**Comment by zonghaishang** [comment]
@fanminshi Thanks for your reply. I have implemented depth control and async watcher notified including auto reconnect by myself.

**Comment by fanminshi** [comment]
@zonghaishang  nice!
