### ISSUE TITLE
com.coreos.jetcd.Watch.Watcher#listen will block thread, I have many watch to listen , How to support callback on jetcd0.0.1 ?

### ISSUE THREAD

**Issue by zonghaishang** [coreos/jetcd#281]
com.coreos.jetcd.Watch.Watcher#listen will block thread, I have many watch to listen , How to support callback on jetcd0.0.1 ?

**Comment by lburgazzoli** [comment]
@fanminshi under the hood watch is already asynchronous so we can _easily_ implement two variants of `Watch::listen`, like:

```java
interface Watch {

    // Modelled on Rx Observable/Flow
    interface EventProcessor {
        void onNext(WatchResponse response);
        void onError(Throwable error);
        void onCompleted();
    }

    interface Watcher {
        CompletableFuture<WatchResponse> listen();
        void listen(WatchEventListener listener);
    }
}

**Comment by fanminshi** [comment]
@lburgazzoli yeah, I agree.

**Comment by fanminshi** [comment]
@lburgazzoli I am hoping to do the 0.0.2 release end of this week. So I think supporting async watcher can be pushed to 0.0.3 milestone.

**Comment by lburgazzoli** [comment]
@fanminshi Yeah no worries, do you want me to work on it ?

**Comment by fanminshi** [comment]
@lburgazzoli go ahead if you are interested! it is a good way to learn about etcd watch semantic!

**Comment by fanminshi** [comment]
tracks async apis in #308
