### ISSUE TITLE
io.grpc.ManagedChannel#notifyWhenStateChanged not implemention yet on jetcd0.0.1 ? 

### ISSUE THREAD

**Issue by zonghaishang** [coreos/jetcd#282]
io.grpc.ManagedChannel#notifyWhenStateChanged not implemention yet on jetcd0.0.1 , but I fount was implemention on master branch, When release next version ?

**Comment by fanminshi** [comment]
working on releasing 0.02 this week. ref: https://github.com/coreos/jetcd/issues/283

**Comment by lburgazzoli** [comment]
@zonghaishang where is it used ?

**Comment by zonghaishang** [comment]
Thanks for your reply, I handled it myself .
