### ISSUE TITLE
0.0.2 release?

### ISSUE THREAD

**Issue by IgorPerikov** [coreos/jetcd#283]
Seems like it was quite a lot of PR's merged since `0.0.1`. What about new release? Or maybe you releasing master branch snapshots to some dedicated repository?

**Comment by fanminshi** [comment]
expect this to be done in this week!

**Comment by fanminshi** [comment]
master branch snapshot is pushed manually!

**Comment by fanminshi** [comment]
I was not able to release the 0.0.2 this week due to technical issue with maven pgp signing and deploy. Will try again next week.

**Comment by lovepoem** [comment]
Waiting for the new version！

**Comment by fanminshi** [comment]
yeah, I am back to it again.

**Comment by fanminshi** [comment]
jetcd v0.0.2 is signed and pushed to maven central:

you can try it out with:
```
    <dependency>
      <groupId>com.coreos</groupId>
      <artifactId>jetcd-core</artifactId>
      <version>0.0.2</version>
    </dependency>
```

I am going to work on writing a release note, updating the readme, update the version to snaphot in thw following days.

**Comment by IgorPerikov** [comment]
Since you have a dedicated issue for tracking all special points - I guess I can close it
