### ISSUE TITLE
License plugin complains about license file with year 2018

### ISSUE THREAD

**Issue by IgorPerikov** [coreos/jetcd#296]
At the moment license plugin verifies license header against concrete text file, I've ran through plugin documentation and found out that it is possible to use configurable files like this
https://github.com/mycila/license-maven-plugin/blob/master/license-maven-plugin/src/main/resources/com/mycila/maven/plugin/license/templates/APACHE-2.txt

but still it doesn't looks like it can support two different years in license header

maybe it's a good idea to just use another goal of this plugin
> license:format: add the license header when missing. If a header is existing, it is updated to the new one.

and connect it to `install` goal or some other with pom year property and configurable license header

**Comment by IgorPerikov** [comment]
I've read more about license headers and copyright date year. Although, I'm not a lawyer, I got to the thought, that header should contain this kind of range `license creation year` - `last year of active development`. So for jetcd it looks like it should be 2017-2018

**Comment by fanminshi** [comment]
`that header should contain this kind of range license creation year - last year of active development.` for license header? hmm, the apache license's template doesn't have a range `Copyright © ${project.inceptionYear} ${owner} (${email})`

**Comment by IgorPerikov** [comment]
yeah, there is no pattern like this described on the plugin website, the only thing I saw is just few *exchange answers. So I decided to look at the spring projects license, here how it looks like
https://github.com/spring-projects/spring-framework/blob/master/spring-jdbc/src/main/java/org/springframework/jdbc/BadSqlGrammarException.java
https://github.com/spring-projects/spring-framework/blob/master/spring-jdbc/src/main/java/org/springframework/jdbc/UncategorizedSQLException.java
Interesting part about spring licensing is that they put first year(example below) even if class was created just few years ago, so maybe it's okay to place the same 'old' header even if file was created few years later
https://github.com/spring-projects/spring-framework/blob/master/spring-webflux/src/main/java/org/springframework/web/reactive/config/CorsRegistration.java
while coreos doesn't update it with the latest commit year
https://github.com/coreos/etcd/blob/master/discovery/discovery.go
Maybe it's a good idea to ask the coreos lawyers.

**Comment by fanminshi** [comment]
good finding! I'll look into this.

**Comment by lburgazzoli** [comment]
@fanminshi have you had any chance to look at this ?

**Comment by fanminshi** [comment]
@lburgazzoli  unfortunately I didn't have time. Do you want to take a stab at this?

**Comment by lburgazzoli** [comment]
I've had a look at what other projectsare doing and apache projects do not even include the year:

- https://github.com/apache/kafka/blob/trunk/core/src/main/scala/kafka/client/ClientUtils.scala
- https://github.com/apache/camel/blob/master/camel-core/src/main/java/org/apache/camel/CamelContext.java
- https://github.com/apache/karaf/blob/master/main/src/main/java/org/apache/karaf/main/Bootstrap.java
- https://github.com/apache/activemq-artemis/blob/master/artemis-server/src/main/java/org/apache/activemq/artemis/core/server/Queue.java

So inception year seems reasonable to me.
