### ISSUE TITLE
Question about WatchCreateRequest.watch_id

### ISSUE THREAD

**Issue by lburgazzoli** [coreos/jetcd#303]
@xiang90 do we have some estimate about when [this](https://github.com/coreos/etcd/commit/9bbfa231831fd556b927e4695c3142f63abcff74) change will be included in an etcd release ? This would make the code much cleaner, see the async implementation [here](https://github.com/lburgazzoli/coreos-jetcd/tree/watch)

**Comment by fanminshi** [comment]
question answered closing..
