### ISSUE TITLE
is client thread safe?

### ISSUE THREAD

**Issue by samaxm** [coreos/jetcd#314]
hi,
i'm using jetcd 0.0.1, is the client(kv and watchclient) thread safe?
should i use a global instance or create every time when use?
what is the best practice when i want to continuously watch some key?(may be in a while(true))
should i create  Watch/Watch.Watcher every turn?

**Comment by lburgazzoli** [comment]
Yes it is, watching is synchronous at the moment, see: https://github.com/coreos/jetcd/blob/master/jetcd-examples/jetcd-watch-example/src/main/java/com/coreos/jetcd/examples/watch/Main.java
