### ISSUE TITLE
how to get sub dir

### ISSUE THREAD

**Issue by timchenxiaoyu** [coreos/jetcd#324]
how to get all  sub dir

for example：/a/b
                        /a/c
how to for each   b and c

**Comment by gyuho** [comment]
Have you tried

https://github.com/coreos/jetcd/blob/ff7d698b046367d243a8d9d5cfe528f9bb0e933f/jetcd-core/src/main/java/com/coreos/jetcd/options/GetOption.java#L169-L174

**Comment by gyuho** [comment]
Or try

https://github.com/coreos/jetcd/blob/ff7d698b046367d243a8d9d5cfe528f9bb0e933f/jetcd-core/src/main/java/com/coreos/jetcd/options/GetOption.java#L154-L157

/cc @fanminshi

**Comment by fanminshi** [comment]
An example on how to use withPrefix option to retrieve all keys that's greater than "/a".

```java
  @Test
  public void testRange() throws Exception {
    ByteSequence a = ByteSequence.fromString("/a");
    ByteSequence b = ByteSequence.fromString("/a/b");
    ByteSequence c = ByteSequence.fromString("/a/c");

    kvClient.put(a, SAMPLE_VALUE).get();
    kvClient.put(b, SAMPLE_VALUE).get();
    kvClient.put(c, SAMPLE_VALUE).get();


    GetResponse resp = kvClient.get(a, GetOption.newBuilder()
        .withPrefix(c)
        .build()).get();

    test.assertEquals(resp.getKvs().size(), 3);
    test.assertEquals(resp.getKvs().get(0).getKey(), a);
    test.assertEquals(resp.getKvs().get(1).getKey(), b);
    test.assertEquals(resp.getKvs().get(2).getKey(), c);
  }
```

**Comment by timchenxiaoyu** [comment]
if I use withPrefix,  I don't know  endkey .  I don't know the sub dir  ?  I only know   /a
