### ISSUE TITLE
"Network closed for unknown reason" when running using java -jar

### ISSUE THREAD

**Issue by gi-wg2** [coreos/jetcd#327]
I get the following exception `io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason` when running a fat jar compiled using the shade plugin in maven or when building from bazel using the _deploy.jar suffix which creates a executable jar for you.

Connecting to the etcd cluster works fine when running the test from intellij using maven, so I suspect there is some dependency issues related to java-grpc.

Have any of you experienced the same problem?

**Comment by gi-wg2** [comment]
That is not enabled on neither the localhost etcd docker or the proxy I am testing against, so that should not be any issue. The same code works when running in Intellij.

**Comment by gi-wg2** [comment]
Any plans to release a new version? Seems like you have fixed a lot of dependencies after the last commit, so would be nice to test with the newest version.

Or do you plan to release up to date snapshot versions?

**Comment by lburgazzoli** [comment]
I'm working to release snapshots

**Comment by lburgazzoli** [comment]
@gi-wg2 snapshots are now published automatically

**Comment by lburgazzoli** [comment]
@gi-wg2 have you been able to test against snapshots ?

**Comment by gi-wg2** [comment]
I haven't, but it seems like this typically is a problem due to dependencies.

For me, it occurred due to versions of dependencies being set in a common dependency management.

**Comment by suhasIVT** [comment]
> Task :run FAILED
Exception in thread "main" io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:233)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:214)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:139)
        at com.oracle.process.deploy.grpc.LibraryServiceGrpc$LibraryServiceBlockingStub.createLibrary(LibraryServiceGrpc.java:576)
        at com.lokesh.grpc.calculator.client.DeployServiceClient.main(DeployServiceClient.java:48)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
