### ISSUE TITLE
How to check whether a java etcd client is available?

### ISSUE THREAD

**Issue by chutian52** [coreos/jetcd#332]
Hi all:
    I only found `close()` method in `Client` api. Is there any way to check if etcd client is available?

**Comment by lburgazzoli** [comment]
what do you mean ?

**Comment by chutian52** [comment]
@lburgazzoli  Just want to determine the client that create can be used without throw any exceptions
```
if(client.isAvailable()){
  kvClient.get(ByteSequence.fromString("/")).get(); 
}
```
I mean pre check befor I use Client Api

**Comment by lburgazzoli** [comment]
Not very sure about what you are trying to achieve, I mean even if the client is "ready", any call such as KV::get can fail or throw exceptions if i.e. the endpoint crashes in between so it looks useless to me.

**Comment by chutian52** [comment]
exactly. Thanks @lburgazzoli
