### ISSUE TITLE
discuss watch client

### ISSUE THREAD

**Issue by StupidHod** [coreos/jetcd#42]
Hi, as discussed in PR #40 , we should discuss about the goals of etcd watch client. 

As my idea, etcd watch is a client to manage watch requests.
Goals:
1. Request watch operation, watch client create watch request for client with key, option(revision, delete only, put only and end key) and register callback for watch request.
2. Notification, when watch client receive event from etcd server, it will call registered callback.
3. Resume,  when the watch client disconnect with etcd server, it will automatically resume all the watch requests and get notification from the latest received revision.
4. Cancel watch request, the etcd client shound cancel watch request when client request and filter all the notification after user request canceled.

Hope for your ideas about watch client, @hongchaodeng @sijie @xiang90 @AdoHe .

**Comment by hongchaodeng** [comment]
I agree with above statements.

The goals we want should be more explicit. Specifically, we want to talk about what we want instead of coding details like methods, instances in #40 .

**Comment by StupidHod** [comment]
Ok, got your advice, so I should add above statements to etcd watch design document.

**Comment by lamuguo** [comment]
What's the status of this one?

**Comment by krestenkrab** [comment]
Hi.  What's the status of the watch client?  `jetcd` is not usable without watches?...

**Comment by fanminshi** [comment]
@krestenkrab, The watch implementation is still in pr https://github.com/coreos/jetcd/pull/45. I will try to get it merged starting Q2; Expect a full speed development on jetcd in Q2.

**Comment by lamuguo** [comment]
StupidHod merge the watch changes in https://github.com/enncloud/jetcd
temporarily, it should be a workable version in his internship. You can
ping him if you get any error in using it.

Best Regards,
Xiaofeng

**Comment by StupidHod** [comment]
@lamuguo  OK, please  ping me with no hesitation.

**Comment by xiang90** [comment]
watcher is implemented
