### ISSUE TITLE
EtcdLease should not use ListenableFuture directly

### ISSUE THREAD

**Issue by oza** [coreos/jetcd#46]
Currently, [EtcdLease](https://github.com/coreos/jetcd/blob/8658eb43e975e69d0030d71147323b5ef37ecb41/src/main/java/com/coreos/jetcd/EtcdLease.java) exposes com.google.common.util.concurrent.ListenableFuture as a part of API. If ListenableFuture is used directly, it will conflict with user-side guava library. Instead, [ListenableSetFuture](https://github.com/StupidHod/jetcd/blob/8d4d09c78aa6029bfabbb3a6cd9c6120c38ba5dd/src/main/java/com/coreos/jetcd/util/ListenableSetFuture.java) in #45 or some wrapper class in com.coreos.jetcd should be used to avoid the problem.

**Comment by lburgazzoli** [comment]
This is related to #16.
IMHO best would be to shade guava and use CompletableFutures as suggested by @jurmous

**Comment by oza** [comment]
@lburgazzoli thanks for the notification. I will also check #16.

I have a patch to shade Guava into jetcd locally, so I can send a PR soon. However, it can increase the size of binary. Can we accept it?

**Comment by lburgazzoli** [comment]
I do not know, but having had quite a few issues with guava dependencies I would really like not to do it again ;)

**Comment by oza** [comment]
Thanks for your comment. I agree with you. Created #47. I appreciate if you take look.

**Comment by fanminshi** [comment]
closing via https://github.com/coreos/jetcd/pull/109
