### ISSUE TITLE
JDK version

### ISSUE THREAD

**Issue by skyao** [coreos/jetcd#5]
One question, which JDK version should we support in jetcd?

java8? or java 7?

**Comment by skyao** [comment]
We decide to java7 now. Now java 8 limitation.

**Comment by skyao** [comment]
Reopen this topic.

For me, java8 is enough. 

I don't know if there is some special requirement for java7.

**Comment by jurmous** [comment]
Java7 is officially not supported anymore and Java 8 would allow to base the async calls on CompletableFuture. On HBase (where I also worked on Netty client besides etcd4j) they did not want to expose Netty futures so they decided to use CompletableFuture as the return. It seems that it is the most future ready way to do async calls. 

https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html

**Comment by AdoHe** [comment]
@skyao I think we need to make a decision about the jdk version from beginning.

**Comment by skyao** [comment]
Java7 is officially not supported anymore.

This is my point to only support java8.

**Comment by lburgazzoli** [comment]
+1 for java 8 only

I also think we should limit as much as possible to expose Guava's specific classes and eventually repackage it as Guava is sometime an issue if another incompatible version is already provided via dependency chain.

**Comment by xiang90** [comment]
OK. Let's do java8 only. Thanks for your opinions.
