### ISSUE TITLE
Ability for client conn to set arbitrary gRPC metadata / HTTP2 request headers 

### ISSUE THREAD

**Issue by jlamillan** [coreos/jetcd#52]
I think it'd be useful for the client to be able to set custom metadata (e.g. HTTP2 request headers) that would be part of the remote call. Basically, a way for the client to set gRPC metadata. It could be abstracted supported something like: 

`Map<String, String> requestHeaders = new HashMap<>();
requestHeaders.put("someKaey", "someValue");
EtcdClient client = EtcdClientBuilder.newBuilder().endpoints("localhost:4004").requestHeaders(requestHeaders).build();
`

**Comment by AdoHe** [comment]
@StupidHod

**Comment by StupidHod** [comment]
Got it, I will take this advice soon.
