### ISSUE TITLE
Missing com.coreos.jetcd.api

### ISSUE THREAD

**Issue by himanshu14049** [coreos/jetcd#54]
Importing jetcd to intellij IDEA cause missing com.coreos.jetcd.api
Anybody faced same issue?

**Comment by AdoHe** [comment]
@himanshu14049 we have not include generated code in repo, so I am afraid you have to generate this by yourself.

**Comment by himanshu14049** [comment]
Could I get the binaries for jetcd?

**Comment by AdoHe** [comment]
@himanshu14049 I am afraid we are not ready to build binary now, watch has not been fully implemented.

**Comment by jaroslavl1** [comment]
Building using Maven resolves this, as some classes need to be generated. If you give the artifact new name, you can publish it to your private Maven repository and use it.

It's not just watches that are missing, EtcdLease seems implemented but not available in EtcdClient

**Comment by fanminshi** [comment]
@himanshu14049 kindly ping?

**Comment by fanminshi** [comment]
reopen if you have more question. just like @jaroslavl1 said. building with maven will generate all the missing `com.coreos.jetcd.api`.
