### ISSUE TITLE
project name about jetcd

### ISSUE THREAD

**Issue by skyao** [coreos/jetcd#6]
There is another java project named jetcd on github and it is a java client for etcd v2.

Do we change to another name? like jetcd3?

**Comment by xiang90** [comment]
let's keep it this way for now. we can change the project name once we plan to do the first release.

**Comment by jurmous** [comment]
I could donate the name etcd4j to you as long as it is versioned 3.x.x (to show which API it supports) and supports async communication. Then I don't mind that it clashes since with the arrival of this official implementation I am not interested to write a v3 api implementation.

**Comment by xiang90** [comment]
jetcd is a friend's project too. I do not think he has enough bandwidth to help on this for the moment.  But I feel he would like to donate the name too if we really want. 

>  as long as it is versioned 3.x.x (to show which API it supports) and supports async communication.

Yea. Right now this jetcd is super uncompleted. None of these are actually supported yet... Let's get the initial release done, and then talk about the naming. :)

/cc @justinsb

**Comment by justinsb** [comment]
Yes, that project is very old, I haven't had time to maintain it, and I don't think anyone is using it.  You should use the name!

I don't _think_ I should just delete the project just in case someone is still using it.  But I could put a big README saying "don't use this - go to coreos/jetcd instead"?

**Comment by skyao** [comment]
Close it and we will reopen it just before we release first version.
