### ISSUE TITLE
Running `mvn package` on master fails

### ISSUE THREAD

**Issue by brettgriffin** [coreos/jetcd#64]
I just checked out master and ran `mvn package` and it appears seven tests are failing:

Failed tests: 
  EtcdAuthClientTest.testRoleAdd:59 » Execution io.grpc.StatusRuntimeException: ...
  EtcdAuthClientTest.testUserAdd:75 » Execution io.grpc.StatusRuntimeException: ...
  EtcdClusterClientTest.testListCluster:32 » Execution io.grpc.StatusRuntimeExce...
  EtcdLeaseTest.testGrant:43 » Execution io.grpc.StatusRuntimeException: UNAVAIL...
  MaintenanceTest.testAlarmList:46 » Execution io.grpc.StatusRuntimeException: U...
  MaintenanceTest.testDefragment:84 » Execution io.grpc.StatusRuntimeException: ...
  MaintenanceTest.testStatusMember:35 » Execution io.grpc.StatusRuntimeException...

Tests run: 37, Failures: 7, Errors: 0, Skipped: 15

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 27.076 s
[INFO] Finished at: 2016-12-17T16:01:27-05:00
[INFO] Final Memory: 40M/666M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project jetcd: There are test failures.

**Comment by StupidHod** [comment]
You should  run  scripts/run_etcd.sh to start a 3 nodes cluster for the test.

**Comment by brettgriffin** [comment]
Hi @StupidHod. I don't want to run a test cluster - I already have a three node etcd cluster running in Kubernetes (using this: https://github.com/coreos/etcd/tree/master/hack/kubernetes-deploy).

I want to use this package in a Maven application. To do this I either need a compiled .jar that I can reference, or I need the Maven dependency entry that is hosted on the public maven registry. It doesn't appear the latter is available, so I'm trying to compile a .jar.
