### ISSUE TITLE
Release for Maven / sbt consumption

### ISSUE THREAD

**Issue by akauppi** [coreos/jetcd#66]
Is jetcd released in some Maven repo? The 'releases' tab in GitHub shows 0.

I am fine by this - can use `mvn install -DskipTests` - but [this](http://stackoverflow.com/questions/40226805/how-to-import-jetcd-in-a-java-playframework-project-using-sbt) StackOverflow entry might benefit from official comments.

**Comment by warnesey333** [comment]
Hey - it would be great if we could get this published to the Maven repo also.

**Comment by jimzli** [comment]
Agreed @warnesey333 - is there any particular reason why there isn't yet a release version as of now?

**Comment by heyitsanthony** [comment]
No release yet due to lack of testing and lack of watch support. Not going to cut a release before the software is ready. Sorry.

**Comment by warnesey333** [comment]
Understood @heyitsanthony  - are there any current plans to implement Watch? Thanks

**Comment by heyitsanthony** [comment]
@warnesey333 yes, planning to ramp up development soon. No firm target release dates, though.

**Comment by bdhess** [comment]
@heyitsanthony are there any pieces where you're either looking for or willing to accept help from the community?  I too would love to see an official release.

**Comment by fanminshi** [comment]
I will add to maven repo when is it production ready. closing.

**Comment by heyitsanthony** [comment]
This is not resolved.

**Comment by fanminshi** [comment]
jetd-core-0.0.1 is pushed to maven central via https://search.maven.org/#search%7Cga%7C1%7Ccoreos
