### ISSUE TITLE
jetcd error

### ISSUE THREAD

**Issue by jolly2** [coreos/jetcd#73]
Hello,
I am trying to use jetcd. However, it needs a lot of dependency jar files. I have downloaded/included all slf4j-1.7.25, protobuf-java-3.2.0, grpc-java-1.0.0,netty-4.1.9.Final JAR files. But, still when running the java program, I am getting "Exception in thread "main" java.lang.NoClassDefFoundError: .io/netty/handler/codec/BinaryHeaders". I am not sure what else need to be included. Is there a list of dependency jars (tree of jars) for jetcd?
Thanks!

**Comment by fanminshi** [comment]
You should build jetcd with maven by running ` mvn clean install -DskipTests=true`. Then you will see a jar file `jetcd-0.1.0-SNAPSHOT.jar` under the `target` folder. 

jetcd is not feature completed yet and still in development, fyi.

**Comment by fanminshi** [comment]
let me know if you have more questions.

**Comment by jolly2** [comment]
Thanks for the response. Now, I am getting no such method error in protobuf...

# java jaytest
Mar 20, 2017 8:22:40 AM io.grpc.internal.ManagedChannelImpl <init>
INFO: [ManagedChannelImpl@457e2f02] Created with target etcd
Exception in thread "main" java.lang.NoSuchMethodError: io.grpc.protobuf.ProtoUtils.marshaller(Lcom/google/protobuf/Message;)Lio/grpc/MethodDescriptor$Marshaller;
        at com.coreos.jetcd.api.KVGrpc.<clinit>(KVGrpc.java:37)
        at com.coreos.jetcd.EtcdKVImpl.<init>(EtcdKVImpl.java:33)
        at com.coreos.jetcd.EtcdClient.lambda$new$1(EtcdClient.java:63)
        at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:160)
        at com.coreos.jetcd.EtcdClient.getKVClient(EtcdClient.java:79)
        at jaytest.main(jaytest.java:17)

I have protobuf-3.0.0 version, grpc-protobuf-1.0.0 version and all the jar files according to pom.xml file in jetcd..
Any suggestion is appreciated.
Thanks!

**Comment by fanminshi** [comment]
@jolly2 just include jars from pom.xml is not enough because those jars also have dependencies. 

You don't need to download those jar manually. You can use maven to download it for you.

cd to jetcd repo dir.

run `mvn dependency:copy-dependencies` will download all dependency jars to target/dependency

run `mvn dependency:copy-dependencies -DincludeScope=runtime` if you don't want to include testing dependencies.

```
ls -l target/dependency/
total 14408
-rw-r--r--  1 fanminshi  staff   368584 Mar 20 12:49 grpc-core-1.0.0.jar
-rw-r--r--  1 fanminshi  staff   119153 Mar 20 12:49 grpc-netty-1.0.0.jar
-rw-r--r--  1 fanminshi  staff     3605 Mar 20 12:49 grpc-protobuf-1.0.0.jar
-rw-r--r--  1 fanminshi  staff     6095 Mar 20 12:49 grpc-protobuf-lite-1.0.0.jar
-rw-r--r--  1 fanminshi  staff    36371 Mar 20 12:49 grpc-stub-1.0.0.jar
-rw-r--r--  1 fanminshi  staff   206853 Mar 20 12:49 gson-2.3.jar
-rw-r--r--  1 fanminshi  staff  2308517 Mar 20 12:49 guava-19.0.jar
-rw-r--r--  1 fanminshi  staff    33031 Mar 20 12:49 jsr305-3.0.0.jar
-rw-r--r--  1 fanminshi  staff   249872 Mar 20 12:49 netty-buffer-4.1.3.Final.jar
-rw-r--r--  1 fanminshi  staff   299078 Mar 20 12:49 netty-codec-4.1.3.Final.jar
-rw-r--r--  1 fanminshi  staff   537334 Mar 20 12:49 netty-codec-http-4.1.3.Final.jar
-rw-r--r--  1 fanminshi  staff   343869 Mar 20 12:49 netty-codec-http2-4.1.3.Final.jar
-rw-r--r--  1 fanminshi  staff   668250 Mar 20 12:49 netty-common-4.1.3.Final.jar
-rw-r--r--  1 fanminshi  staff   302860 Mar 20 12:49 netty-handler-4.1.3.Final.jar
-rw-r--r--  1 fanminshi  staff    25653 Mar 20 12:49 netty-resolver-4.1.3.Final.jar
-rw-r--r--  1 fanminshi  staff   417558 Mar 20 12:49 netty-transport-4.1.3.Final.jar
-rw-r--r--  1 fanminshi  staff  1304430 Mar 20 12:49 protobuf-java-3.0.0.jar
-rw-r--r--  1 fanminshi  staff    64530 Mar 20 12:49 protobuf-java-util-3.0.0.jar
-rw-r--r--  1 fanminshi  staff    41071 Mar 20 12:49 slf4j-api-1.7.21.jar
```

In order to use jetcd, you need to build a jetcd jar using `mvn clean install -DskipTests=true`.
Then include the jetcd jar along with its dependencies to the new project. 

Let me know if you have more questions.

**Comment by fanminshi** [comment]
@jolly2 kindly ping?

**Comment by fanminshi** [comment]
@jolly2 reopen this if you have more questions.
