### ISSUE TITLE
LeaseGrpc and KVGrpc cannot be generated from proto

### ISSUE THREAD

**Issue by atmlvs** [coreos/jetcd#81]
com.coreos.jetcd.api.KVGrpc and com.coreos.jetcd.api.LeaseGrpc cannot be generated from auth.proto, kv.proto and rpc.proto by protoc-3.0.0-win32.
I used the latest version of master, if any configuration missed?

**Comment by heyitsanthony** [comment]
@atmlvs what commands did you use to generate the grpc stubs? What errors are being returned?

**Comment by fanminshi** [comment]
@atmlvs kindly ping?

**Comment by smartminghan** [comment]
i also can't generate KVGrpc and LeaseGrpc. seems the proto file lack the definition of the them? can u help to provide?

**Comment by fanminshi** [comment]
@smartminghan how are you generating KVGrpc and LeaseGrpc? Are you using maven to build jetcd? jetcd pom.xml includes plugin that generate protobuf automatically if you run
 ```sh
$ mvn install -Dmaven.test.skip=true
...
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16.956 s
[INFO] Finished at: 2017-06-09T13:44:06-07:00
[INFO] Final Memory: 37M/352M
[INFO] ------------------------------------------------------------------------
```

```sh
$ tree target/generated-sources/protobuf/grpc-java/
target/generated-sources/protobuf/grpc-java/
└── com
    └── coreos
        └── jetcd
            └── api
                ├── AuthGrpc.java
                ├── ClusterGrpc.java
                ├── KVGrpc.java
                ├── LeaseGrpc.java
                ├── MaintenanceGrpc.java
                └── WatchGrpc.java
```

**Comment by fanminshi** [comment]
@smartminghan kindly ping?

**Comment by fanminshi** [comment]
closing due to no activities. reopen if you have more questions.

**Comment by smartminghan** [comment]
It works. Thanks.

**Comment by smartminghan** [comment]
Btw, may i know if ByteSequence is necessary?  GRPC interface require us to input ByteString param as key and value. why not just directly use ByteString.copyFrom("targetString")  to return ByteString ?
