### ISSUE TITLE
set up initial testing infrastructure 

### ISSUE THREAD

**Issue by xiang90** [coreos/jetcd#9]
We probably just want to use a real etcd cluster for testing instead of mocking it for now.

Something like this https://github.com/justinsb/jetcd/blob/master/scripts/run_etcd.sh should be good enough.

**Comment by lburgazzoli** [comment]
See also:
- https://github.com/jurmous/etcd4j/tree/master/src/main/bash
- https://github.com/jurmous/etcd4j/blob/master/.travis.yml

Another option would be to run the official docker image i.e: 
- https://docs.travis-ci.com/user/docker/

**Comment by xiang90** [comment]
this is finished.
