### ISSUE TITLE
the add-source config in pom.xml is error

### ISSUE THREAD

**Issue by chenyouhuang** [coreos/jetcd#92]
`<goals>
	<goal>add-source</goal>
</goals>
<configuration>
	<sources>
		<source>${basedir}/target/generated-sources</source>
	</sources>
</configuration>`

I think this config above is incorrect.
It must change to config like below：
`<goals>
    <goal>add-source</goal>
</goals>
<configuration>
    <sources>
        <source>${basedir}/target/generated-sources/protobuf/java</source>
        <source>${basedir}/target/generated-sources/protobuf/grpc-java</source>
    </sources>
</configuration>`

so it can find the correct source folder.

**Comment by fanminshi** [comment]
@chenyouhuang are you experiencing any errors?
 I did a `mvn clean` and `mvn install -DskipTests` and see no build errors with the current pom config.

**Comment by fanminshi** [comment]
@chenyouhuang kindly ping?

**Comment by fanminshi** [comment]
reopen if you have more questions. thanks.
