### ISSUE TITLE
How to do service discovery with jetcd?

### ISSUE THREAD

**Issue by ncubrian** [coreos/jetcd#97]
I'm trying to implement a micro service demo using etcd as service registry center. Assume I have deployed three etcd nodes, which are 192.168.99.11:2379, 192.168.99.22:2379 and 192.168.99.33:2379, along with a service process deployed on each node. 

The service process on each node is listening on port 9999 and registered in the etcd cluster with keys /etcd3/foo/192.168.99.11:9999, /etcd3/foo/192.168.99.22:9999 and /etcd3/foo/192.168.99.33:9999. 

My question is how to use java gRPC and jetcd to discover the list of three service nodes and do rpc call with round robin load balancing. I've tried many ways only to find the NameResolver really confuses me and EtcdKV doesn't support get with prefix. I can't get the service list from key /etcd3/foo/ without get with prefix. However, I can get the service list from key /etcd3/foo/ on command line using etcdctl get --prefix /etcd3/foo/.

Better show me some sample codes. It's kinda urgent. Thanks in advance!

**Comment by fanminshi** [comment]
@ncubrian once this pr gets merged, https://github.com/coreos/jetcd/pull/79. EtcdKV will have the prefix option. I'll take a look of how NameResolver works.

**Comment by fanminshi** [comment]
@ncubrian I think you need a NameResolver that uses etcd client to retrieve service endpoints under `/etcd3/foo/`. Then you need use that NamerResolver to build a java gRPC that would retrieve the endpoint from etcd and attempt to make connections with those.  Currently, Jetcd doesn't have that NameResolver implemented. When EtcdKV prefix feature gets merged, then It is possible to implement such NameResolver. It probably will be implemented in the future as the official etcd go client already has that feature. https://github.com/coreos/etcd/blob/master/clientv3/naming/grpc.go#L32.

**Comment by ncubrian** [comment]
@fanminshi Thanks to your advise I implemented a service discovery demo by rewriting the SimpleEtcdNameResolver and it actually works. Oh btw, I found that getWithPrefix is just get with range_end option which is just one bit larger than the key :)

**Comment by fanminshi** [comment]
@ncubrian that's very nice! Let me know if you have more questions.

**Comment by fanminshi** [comment]
closing. re-open if you have more questions.
